# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ctcUI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1601, 614)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scheduledTrains = QCheckBox(self.centralwidget)
        self.scheduledTrains.setObjectName(u"scheduledTrains")
        self.scheduledTrains.setGeometry(QRect(160, 70, 111, 22))
        self.legendLabel_3 = QLabel(self.centralwidget)
        self.legendLabel_3.setObjectName(u"legendLabel_3")
        self.legendLabel_3.setGeometry(QRect(510, 360, 101, 16))
        self.legendLabel = QLabel(self.centralwidget)
        self.legendLabel.setObjectName(u"legendLabel")
        self.legendLabel.setGeometry(QRect(490, 310, 101, 16))
        self.checkButton = QPushButton(self.centralwidget)
        self.checkButton.setObjectName(u"checkButton")
        self.checkButton.setGeometry(QRect(430, 410, 31, 24))
        self.blockSelectMaintenance = QComboBox(self.centralwidget)
        self.blockSelectMaintenance.setObjectName(u"blockSelectMaintenance")
        self.blockSelectMaintenance.setGeometry(QRect(410, 350, 51, 21))
        self.time1x = QPushButton(self.centralwidget)
        self.time1x.setObjectName(u"time1x")
        self.time1x.setGeometry(QRect(390, 450, 31, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(480, 330, 21, 16))
        self.label.setStyleSheet(u"background-color: green\n"
"")
        self.Outline2_2 = QFrame(self.centralwidget)
        self.Outline2_2.setObjectName(u"Outline2_2")
        self.Outline2_2.setGeometry(QRect(310, 40, 151, 21))
        self.Outline2_2.setAutoFillBackground(False)
        self.Outline2_2.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2_2.setFrameShape(QFrame.StyledPanel)
        self.Outline2_2.setFrameShadow(QFrame.Raised)
        self.optionsLabel_2 = QLabel(self.Outline2_2)
        self.optionsLabel_2.setObjectName(u"optionsLabel_2")
        self.optionsLabel_2.setGeometry(QRect(20, 1, 121, 16))
        font = QFont()
        font.setPointSize(10)
        self.optionsLabel_2.setFont(font)
        self.optionsLabel_2.setStyleSheet(u"color: black")
        self.uploadSchedule = QPushButton(self.centralwidget)
        self.uploadSchedule.setObjectName(u"uploadSchedule")
        self.uploadSchedule.setGeometry(QRect(430, 450, 101, 24))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(480, 390, 21, 16))
        self.label_3.setStyleSheet(u"background-color: Gold\n"
"")
        self.Outline = QFrame(self.centralwidget)
        self.Outline.setObjectName(u"Outline")
        self.Outline.setGeometry(QRect(10, 10, 281, 51))
        self.Outline.setAutoFillBackground(False)
        self.Outline.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline.setFrameShape(QFrame.StyledPanel)
        self.Outline.setFrameShadow(QFrame.Raised)
        self.DispatchTrain = QLabel(self.Outline)
        self.DispatchTrain.setObjectName(u"DispatchTrain")
        self.DispatchTrain.setGeometry(QRect(70, 10, 141, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.DispatchTrain.setFont(font1)
        self.DispatchTrain.setStyleSheet(u"color: black")
        self.blockLabel_2 = QLabel(self.centralwidget)
        self.blockLabel_2.setObjectName(u"blockLabel_2")
        self.blockLabel_2.setGeometry(QRect(420, 330, 31, 16))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(470, 300, 151, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 100, 281, 441))
        self.greenLinePage = QWidget()
        self.greenLinePage.setObjectName(u"greenLinePage")
        self.greenClear = QPushButton(self.greenLinePage)
        self.greenClear.setObjectName(u"greenClear")
        self.greenClear.setGeometry(QRect(20, 320, 61, 21))
        self.greenClear.setStyleSheet(u"background-color: Red; color: Black")
        self.greenDispatch = QPushButton(self.greenLinePage)
        self.greenDispatch.setObjectName(u"greenDispatch")
        self.greenDispatch.setGeometry(QRect(100, 320, 61, 21))
        self.greenDispatch.setStyleSheet(u"background-color: Green; color: Black")
        self.arrivalLabel_3 = QLabel(self.greenLinePage)
        self.arrivalLabel_3.setObjectName(u"arrivalLabel_3")
        self.arrivalLabel_3.setGeometry(QRect(20, 111, 161, 20))
        self.greenTentSchedule = QTableWidget(self.greenLinePage)
        if (self.greenTentSchedule.columnCount() < 2):
            self.greenTentSchedule.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.greenTentSchedule.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.greenTentSchedule.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.greenTentSchedule.setObjectName(u"greenTentSchedule")
        self.greenTentSchedule.setGeometry(QRect(20, 130, 141, 181))
        self.greenDestination = QLineEdit(self.greenLinePage)
        self.greenDestination.setObjectName(u"greenDestination")
        self.greenDestination.setGeometry(QRect(20, 40, 113, 24))
        self.greenTime = QLineEdit(self.greenLinePage)
        self.greenTime.setObjectName(u"greenTime")
        self.greenTime.setGeometry(QRect(160, 40, 71, 24))
        self.greenAddStop = QPushButton(self.greenLinePage)
        self.greenAddStop.setObjectName(u"greenAddStop")
        self.greenAddStop.setGeometry(QRect(110, 80, 71, 21))
        self.greenAddStop.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.blockLabel_6 = QLabel(self.greenLinePage)
        self.blockLabel_6.setObjectName(u"blockLabel_6")
        self.blockLabel_6.setGeometry(QRect(20, 20, 81, 21))
        self.blockLabel_7 = QLabel(self.greenLinePage)
        self.blockLabel_7.setObjectName(u"blockLabel_7")
        self.blockLabel_7.setGeometry(QRect(160, 20, 91, 21))
        self.stackedWidget.addWidget(self.greenLinePage)
        self.redLinePage = QWidget()
        self.redLinePage.setObjectName(u"redLinePage")
        self.redClear = QPushButton(self.redLinePage)
        self.redClear.setObjectName(u"redClear")
        self.redClear.setGeometry(QRect(20, 320, 61, 21))
        self.redClear.setStyleSheet(u"background-color: Red; color: Black")
        self.redDispatch = QPushButton(self.redLinePage)
        self.redDispatch.setObjectName(u"redDispatch")
        self.redDispatch.setGeometry(QRect(170, 320, 61, 21))
        self.redDispatch.setStyleSheet(u"background-color: Green; color: Black")
        self.arrivalLabel_4 = QLabel(self.redLinePage)
        self.arrivalLabel_4.setObjectName(u"arrivalLabel_4")
        self.arrivalLabel_4.setGeometry(QRect(20, 110, 151, 20))
        self.redTentSchedule = QTableWidget(self.redLinePage)
        if (self.redTentSchedule.columnCount() < 2):
            self.redTentSchedule.setColumnCount(2)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.redTentSchedule.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.redTentSchedule.setHorizontalHeaderItem(1, __qtablewidgetitem3)
        self.redTentSchedule.setObjectName(u"redTentSchedule")
        self.redTentSchedule.setGeometry(QRect(20, 130, 211, 181))
        self.blockLabel_8 = QLabel(self.redLinePage)
        self.blockLabel_8.setObjectName(u"blockLabel_8")
        self.blockLabel_8.setGeometry(QRect(160, 20, 91, 21))
        self.blockLabel_9 = QLabel(self.redLinePage)
        self.blockLabel_9.setObjectName(u"blockLabel_9")
        self.blockLabel_9.setGeometry(QRect(20, 20, 81, 21))
        self.redDestination = QLineEdit(self.redLinePage)
        self.redDestination.setObjectName(u"redDestination")
        self.redDestination.setGeometry(QRect(20, 40, 113, 24))
        self.redTime = QLineEdit(self.redLinePage)
        self.redTime.setObjectName(u"redTime")
        self.redTime.setGeometry(QRect(160, 40, 71, 24))
        self.redAddStop = QPushButton(self.redLinePage)
        self.redAddStop.setObjectName(u"redAddStop")
        self.redAddStop.setGeometry(QRect(110, 80, 71, 21))
        self.redAddStop.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.stackedWidget.addWidget(self.redLinePage)
        self.scheduledPage = QWidget()
        self.scheduledPage.setObjectName(u"scheduledPage")
        self.arrivalLabel_5 = QLabel(self.scheduledPage)
        self.arrivalLabel_5.setObjectName(u"arrivalLabel_5")
        self.arrivalLabel_5.setGeometry(QRect(0, 0, 161, 20))
        self.arrivalLabel_6 = QLabel(self.scheduledPage)
        self.arrivalLabel_6.setObjectName(u"arrivalLabel_6")
        self.arrivalLabel_6.setGeometry(QRect(0, 210, 141, 20))
        self.greenScheduledTrains = QTableWidget(self.scheduledPage)
        if (self.greenScheduledTrains.columnCount() < 4):
            self.greenScheduledTrains.setColumnCount(4)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.greenScheduledTrains.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.greenScheduledTrains.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.greenScheduledTrains.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.greenScheduledTrains.setHorizontalHeaderItem(3, __qtablewidgetitem7)
        self.greenScheduledTrains.setObjectName(u"greenScheduledTrains")
        self.greenScheduledTrains.setGeometry(QRect(0, 20, 281, 171))
        self.redScheduledTrains = QTableWidget(self.scheduledPage)
        if (self.redScheduledTrains.columnCount() < 3):
            self.redScheduledTrains.setColumnCount(3)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.redScheduledTrains.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.redScheduledTrains.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.redScheduledTrains.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        self.redScheduledTrains.setObjectName(u"redScheduledTrains")
        self.redScheduledTrains.setGeometry(QRect(0, 230, 281, 171))
        self.stackedWidget.addWidget(self.scheduledPage)
        self.trackSwitchStates = QWidget()
        self.trackSwitchStates.setObjectName(u"trackSwitchStates")
        self.blockLabel_5 = QLabel(self.trackSwitchStates)
        self.blockLabel_5.setObjectName(u"blockLabel_5")
        self.blockLabel_5.setGeometry(QRect(120, 200, 51, 21))
        self.red_text_H4 = QLabel(self.trackSwitchStates)
        self.red_text_H4.setObjectName(u"red_text_H4")
        self.red_text_H4.setGeometry(QRect(30, 370, 16, 16))
        self.green_text_C = QLabel(self.trackSwitchStates)
        self.green_text_C.setObjectName(u"green_text_C")
        self.green_text_C.setGeometry(QRect(30, 20, 16, 16))
        self.green_M1 = QPushButton(self.trackSwitchStates)
        self.green_M1.setObjectName(u"green_M1")
        self.green_M1.setGeometry(QRect(70, 140, 80, 24))
        self.green_M2 = QPushButton(self.trackSwitchStates)
        self.green_M2.setObjectName(u"green_M2")
        self.green_M2.setGeometry(QRect(150, 140, 80, 24))
        self.red_C1 = QPushButton(self.trackSwitchStates)
        self.red_C1.setObjectName(u"red_C1")
        self.red_C1.setGeometry(QRect(70, 220, 80, 24))
        self.red_H2_2 = QPushButton(self.trackSwitchStates)
        self.red_H2_2.setObjectName(u"red_H2_2")
        self.red_H2_2.setGeometry(QRect(150, 310, 80, 24))
        self.red_H3_1 = QPushButton(self.trackSwitchStates)
        self.red_H3_1.setObjectName(u"red_H3_1")
        self.red_H3_1.setGeometry(QRect(70, 340, 80, 24))
        self.green_text_N = QLabel(self.trackSwitchStates)
        self.green_text_N.setObjectName(u"green_text_N")
        self.green_text_N.setGeometry(QRect(30, 170, 16, 16))
        self.red_H1_1 = QPushButton(self.trackSwitchStates)
        self.red_H1_1.setObjectName(u"red_H1_1")
        self.red_H1_1.setGeometry(QRect(70, 280, 80, 24))
        self.green_N2 = QPushButton(self.trackSwitchStates)
        self.green_N2.setObjectName(u"green_N2")
        self.green_N2.setGeometry(QRect(150, 170, 80, 24))
        self.red_H4_1 = QPushButton(self.trackSwitchStates)
        self.red_H4_1.setObjectName(u"red_H4_1")
        self.red_H4_1.setGeometry(QRect(70, 370, 80, 24))
        self.red_J1 = QPushButton(self.trackSwitchStates)
        self.red_J1.setObjectName(u"red_J1")
        self.red_J1.setGeometry(QRect(70, 400, 80, 24))
        self.red_text_E = QLabel(self.trackSwitchStates)
        self.red_text_E.setObjectName(u"red_text_E")
        self.red_text_E.setGeometry(QRect(30, 250, 16, 16))
        self.green_text_G = QLabel(self.trackSwitchStates)
        self.green_text_G.setObjectName(u"green_text_G")
        self.green_text_G.setGeometry(QRect(30, 50, 16, 16))
        self.green_J1_1 = QPushButton(self.trackSwitchStates)
        self.green_J1_1.setObjectName(u"green_J1_1")
        self.green_J1_1.setGeometry(QRect(70, 80, 80, 24))
        self.green_text_J2 = QLabel(self.trackSwitchStates)
        self.green_text_J2.setObjectName(u"green_text_J2")
        self.green_text_J2.setGeometry(QRect(30, 110, 16, 16))
        self.red_H1_2 = QPushButton(self.trackSwitchStates)
        self.red_H1_2.setObjectName(u"red_H1_2")
        self.red_H1_2.setGeometry(QRect(150, 280, 80, 24))
        self.red_text_H1 = QLabel(self.trackSwitchStates)
        self.red_text_H1.setObjectName(u"red_text_H1")
        self.red_text_H1.setGeometry(QRect(30, 280, 16, 16))
        self.red_textH3 = QLabel(self.trackSwitchStates)
        self.red_textH3.setObjectName(u"red_textH3")
        self.red_textH3.setGeometry(QRect(30, 340, 16, 16))
        self.red_textH2 = QLabel(self.trackSwitchStates)
        self.red_textH2.setObjectName(u"red_textH2")
        self.red_textH2.setGeometry(QRect(30, 310, 16, 16))
        self.red_H2_1 = QPushButton(self.trackSwitchStates)
        self.red_H2_1.setObjectName(u"red_H2_1")
        self.red_H2_1.setGeometry(QRect(70, 310, 80, 24))
        self.green_G1 = QPushButton(self.trackSwitchStates)
        self.green_G1.setObjectName(u"green_G1")
        self.green_G1.setGeometry(QRect(70, 50, 80, 24))
        self.red_E2 = QPushButton(self.trackSwitchStates)
        self.red_E2.setObjectName(u"red_E2")
        self.red_E2.setGeometry(QRect(150, 250, 80, 24))
        self.green_J2_1 = QPushButton(self.trackSwitchStates)
        self.green_J2_1.setObjectName(u"green_J2_1")
        self.green_J2_1.setGeometry(QRect(70, 110, 80, 24))
        self.red_J2 = QPushButton(self.trackSwitchStates)
        self.red_J2.setObjectName(u"red_J2")
        self.red_J2.setGeometry(QRect(150, 400, 80, 24))
        self.red_text_J = QLabel(self.trackSwitchStates)
        self.red_text_J.setObjectName(u"red_text_J")
        self.red_text_J.setGeometry(QRect(30, 400, 16, 16))
        self.red_C2 = QPushButton(self.trackSwitchStates)
        self.red_C2.setObjectName(u"red_C2")
        self.red_C2.setGeometry(QRect(150, 220, 80, 24))
        self.red_H4_2 = QPushButton(self.trackSwitchStates)
        self.red_H4_2.setObjectName(u"red_H4_2")
        self.red_H4_2.setGeometry(QRect(150, 370, 80, 24))
        self.green_J1_2 = QPushButton(self.trackSwitchStates)
        self.green_J1_2.setObjectName(u"green_J1_2")
        self.green_J1_2.setGeometry(QRect(150, 80, 80, 24))
        self.red_E1 = QPushButton(self.trackSwitchStates)
        self.red_E1.setObjectName(u"red_E1")
        self.red_E1.setGeometry(QRect(70, 250, 80, 24))
        self.red_text_C = QLabel(self.trackSwitchStates)
        self.red_text_C.setObjectName(u"red_text_C")
        self.red_text_C.setGeometry(QRect(30, 220, 16, 16))
        self.green_G2 = QPushButton(self.trackSwitchStates)
        self.green_G2.setObjectName(u"green_G2")
        self.green_G2.setGeometry(QRect(150, 50, 80, 24))
        self.green_N1 = QPushButton(self.trackSwitchStates)
        self.green_N1.setObjectName(u"green_N1")
        self.green_N1.setGeometry(QRect(70, 170, 80, 24))
        self.green_text_J1 = QLabel(self.trackSwitchStates)
        self.green_text_J1.setObjectName(u"green_text_J1")
        self.green_text_J1.setGeometry(QRect(30, 80, 16, 16))
        self.green_J2_2 = QPushButton(self.trackSwitchStates)
        self.green_J2_2.setObjectName(u"green_J2_2")
        self.green_J2_2.setGeometry(QRect(150, 110, 80, 24))
        self.red_H3_2 = QPushButton(self.trackSwitchStates)
        self.red_H3_2.setObjectName(u"red_H3_2")
        self.red_H3_2.setGeometry(QRect(150, 340, 80, 24))
        self.green_text_M = QLabel(self.trackSwitchStates)
        self.green_text_M.setObjectName(u"green_text_M")
        self.green_text_M.setGeometry(QRect(30, 140, 16, 16))
        self.blockLabel_4 = QLabel(self.trackSwitchStates)
        self.blockLabel_4.setObjectName(u"blockLabel_4")
        self.blockLabel_4.setGeometry(QRect(110, 0, 61, 21))
        self.green_C2 = QPushButton(self.trackSwitchStates)
        self.green_C2.setObjectName(u"green_C2")
        self.green_C2.setGeometry(QRect(150, 20, 80, 24))
        self.green_C1 = QPushButton(self.trackSwitchStates)
        self.green_C1.setObjectName(u"green_C1")
        self.green_C1.setGeometry(QRect(70, 20, 80, 24))
        self.stackedWidget.addWidget(self.trackSwitchStates)
        self.legendLabel_2 = QLabel(self.centralwidget)
        self.legendLabel_2.setObjectName(u"legendLabel_2")
        self.legendLabel_2.setGeometry(QRect(510, 330, 101, 16))
        self.modesText = QLabel(self.centralwidget)
        self.modesText.setObjectName(u"modesText")
        self.modesText.setGeometry(QRect(310, 500, 41, 21))
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(470, 420, 151, 21))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.time10x = QPushButton(self.centralwidget)
        self.time10x.setObjectName(u"time10x")
        self.time10x.setGeometry(QRect(360, 470, 31, 21))
        self.dataTime = QLabel(self.centralwidget)
        self.dataTime.setObjectName(u"dataTime")
        self.dataTime.setGeometry(QRect(310, 450, 51, 16))
        self.dispatchGreen = QCheckBox(self.centralwidget)
        self.dispatchGreen.setObjectName(u"dispatchGreen")
        self.dispatchGreen.setGeometry(QRect(10, 70, 78, 22))
        self.Outline2 = QFrame(self.centralwidget)
        self.Outline2.setObjectName(u"Outline2")
        self.Outline2.setGeometry(QRect(310, 310, 151, 21))
        self.Outline2.setAutoFillBackground(False)
        self.Outline2.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2.setFrameShape(QFrame.StyledPanel)
        self.Outline2.setFrameShadow(QFrame.Raised)
        self.optionsLabel = QLabel(self.Outline2)
        self.optionsLabel.setObjectName(u"optionsLabel")
        self.optionsLabel.setGeometry(QRect(20, 1, 121, 16))
        self.optionsLabel.setFont(font)
        self.optionsLabel.setStyleSheet(u"color: black")
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(610, 310, 20, 121))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.legendLabel_4 = QLabel(self.centralwidget)
        self.legendLabel_4.setObjectName(u"legendLabel_4")
        self.legendLabel_4.setGeometry(QRect(510, 390, 81, 31))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(480, 360, 21, 16))
        self.label_2.setStyleSheet(u"background-color: red\n"
"")
        self.dispatchRed = QCheckBox(self.centralwidget)
        self.dispatchRed.setObjectName(u"dispatchRed")
        self.dispatchRed.setGeometry(QRect(90, 70, 71, 22))
        self.maintenanceSelect = QCheckBox(self.centralwidget)
        self.maintenanceSelect.setObjectName(u"maintenanceSelect")
        self.maintenanceSelect.setGeometry(QRect(510, 500, 91, 22))
        self.autoSelect = QCheckBox(self.centralwidget)
        self.autoSelect.setObjectName(u"autoSelect")
        self.autoSelect.setGeometry(QRect(360, 500, 78, 22))
        self.Outline2_3 = QFrame(self.centralwidget)
        self.Outline2_3.setObjectName(u"Outline2_3")
        self.Outline2_3.setGeometry(QRect(310, 170, 151, 21))
        self.Outline2_3.setAutoFillBackground(False)
        self.Outline2_3.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2_3.setFrameShape(QFrame.StyledPanel)
        self.Outline2_3.setFrameShadow(QFrame.Raised)
        self.optionsLabel_3 = QLabel(self.Outline2_3)
        self.optionsLabel_3.setObjectName(u"optionsLabel_3")
        self.optionsLabel_3.setGeometry(QRect(20, 1, 121, 16))
        self.optionsLabel_3.setFont(font)
        self.optionsLabel_3.setStyleSheet(u"color: black")
        self.lineSelectMaintenance = QComboBox(self.centralwidget)
        self.lineSelectMaintenance.setObjectName(u"lineSelectMaintenance")
        self.lineSelectMaintenance.setGeometry(QRect(310, 350, 71, 21))
        self.manualSelect = QCheckBox(self.centralwidget)
        self.manualSelect.setObjectName(u"manualSelect")
        self.manualSelect.setGeometry(QRect(440, 500, 61, 22))
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(460, 310, 20, 121))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.modeSelect = QComboBox(self.centralwidget)
        self.modeSelect.addItem("")
        self.modeSelect.addItem("")
        self.modeSelect.setObjectName(u"modeSelect")
        self.modeSelect.setGeometry(QRect(310, 380, 151, 21))
        self.xButton = QPushButton(self.centralwidget)
        self.xButton.setObjectName(u"xButton")
        self.xButton.setGeometry(QRect(390, 410, 31, 24))
        self.lineLabel = QLabel(self.centralwidget)
        self.lineLabel.setObjectName(u"lineLabel")
        self.lineLabel.setGeometry(QRect(330, 330, 31, 16))
        self.redOccupancy = QTableWidget(self.centralwidget)
        if (self.redOccupancy.columnCount() < 3):
            self.redOccupancy.setColumnCount(3)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        self.redOccupancy.setObjectName(u"redOccupancy")
        self.redOccupancy.setGeometry(QRect(1190, 60, 401, 501))
        self.greenOccupancy = QTableWidget(self.centralwidget)
        if (self.greenOccupancy.columnCount() < 3):
            self.greenOccupancy.setColumnCount(3)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(2, __qtablewidgetitem16)
        self.greenOccupancy.setObjectName(u"greenOccupancy")
        self.greenOccupancy.setGeometry(QRect(790, 60, 401, 501))
        self.time50x = QPushButton(self.centralwidget)
        self.time50x.setObjectName(u"time50x")
        self.time50x.setGeometry(QRect(390, 470, 31, 21))
        self.timePause = QPushButton(self.centralwidget)
        self.timePause.setObjectName(u"timePause")
        self.timePause.setGeometry(QRect(360, 450, 31, 21))
        self.greenOccupancyText = QLabel(self.centralwidget)
        self.greenOccupancyText.setObjectName(u"greenOccupancyText")
        self.greenOccupancyText.setGeometry(QRect(900, 10, 181, 41))
        self.greenOccupancyText.setStyleSheet(u"background-color: LightGreen; color: Black")
        self.redOccupancyText = QLabel(self.centralwidget)
        self.redOccupancyText.setObjectName(u"redOccupancyText")
        self.redOccupancyText.setGeometry(QRect(1300, 10, 181, 41))
        self.redOccupancyText.setStyleSheet(u"background-color: LightCoral; color: Black")
        self.thisIsATest = QPushButton(self.centralwidget)
        self.thisIsATest.setObjectName(u"thisIsATest")
        self.thisIsATest.setGeometry(QRect(310, 530, 71, 24))
        self.greenTrainInfoTable = QTableWidget(self.centralwidget)
        if (self.greenTrainInfoTable.columnCount() < 4):
            self.greenTrainInfoTable.setColumnCount(4)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(0, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(1, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(2, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(3, __qtablewidgetitem20)
        self.greenTrainInfoTable.setObjectName(u"greenTrainInfoTable")
        self.greenTrainInfoTable.setGeometry(QRect(310, 60, 461, 101))
        self.redTrainInfoTable = QTableWidget(self.centralwidget)
        if (self.redTrainInfoTable.columnCount() < 4):
            self.redTrainInfoTable.setColumnCount(4)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(0, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(1, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(2, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(3, __qtablewidgetitem24)
        self.redTrainInfoTable.setObjectName(u"redTrainInfoTable")
        self.redTrainInfoTable.setGeometry(QRect(310, 190, 461, 101))
        self.blockLabel_10 = QLabel(self.centralwidget)
        self.blockLabel_10.setObjectName(u"blockLabel_10")
        self.blockLabel_10.setGeometry(QRect(630, 310, 131, 21))
        self.blockLabel_11 = QLabel(self.centralwidget)
        self.blockLabel_11.setObjectName(u"blockLabel_11")
        self.blockLabel_11.setGeometry(QRect(630, 330, 61, 21))
        self.blockLabel_12 = QLabel(self.centralwidget)
        self.blockLabel_12.setObjectName(u"blockLabel_12")
        self.blockLabel_12.setGeometry(QRect(630, 350, 51, 21))
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(630, 320, 141, 21))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(630, 300, 141, 21))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(620, 310, 20, 61))
        self.line_9.setFrameShape(QFrame.VLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(630, 360, 141, 21))
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.redThroughput = QLabel(self.centralwidget)
        self.redThroughput.setObjectName(u"redThroughput")
        self.redThroughput.setGeometry(QRect(690, 350, 91, 21))
        self.greenThroughput = QLabel(self.centralwidget)
        self.greenThroughput.setObjectName(u"greenThroughput")
        self.greenThroughput.setGeometry(QRect(690, 330, 91, 21))
        self.line_11 = QFrame(self.centralwidget)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(760, 310, 20, 61))
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(590, 460, 80, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1601, 21))
        self.menuNorth_Shore_Extension_CTC_Window = QMenu(self.menubar)
        self.menuNorth_Shore_Extension_CTC_Window.setObjectName(u"menuNorth_Shore_Extension_CTC_Window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuNorth_Shore_Extension_CTC_Window.menuAction())

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.scheduledTrains.setText(QCoreApplication.translate("MainWindow", u"Scheduled Trains", None))
        self.legendLabel_3.setText(QCoreApplication.translate("MainWindow", u"- Train authority", None))
        self.legendLabel.setText(QCoreApplication.translate("MainWindow", u"Occupancy Legend", None))
        self.checkButton.setText(QCoreApplication.translate("MainWindow", u"\u2713", None))
        self.time1x.setText(QCoreApplication.translate("MainWindow", u"1x", None))
        self.label.setText("")
        self.optionsLabel_2.setText(QCoreApplication.translate("MainWindow", u"Green Line Train Info", None))
        self.uploadSchedule.setText(QCoreApplication.translate("MainWindow", u"Upload Schedule", None))
        self.label_3.setText("")
        self.DispatchTrain.setText(QCoreApplication.translate("MainWindow", u"Dispatch Train", None))
        self.blockLabel_2.setText(QCoreApplication.translate("MainWindow", u"Block", None))
        self.greenClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.greenDispatch.setText(QCoreApplication.translate("MainWindow", u"Dispatch", None))
        self.arrivalLabel_3.setText(QCoreApplication.translate("MainWindow", u"Green Line Tentative Schedule:", None))
        ___qtablewidgetitem = self.greenTentSchedule.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Dest.", None));
        ___qtablewidgetitem1 = self.greenTentSchedule.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"AT", None));
        self.greenAddStop.setText(QCoreApplication.translate("MainWindow", u"Add Stop", None))
        self.blockLabel_6.setText(QCoreApplication.translate("MainWindow", u"Destination:", None))
        self.blockLabel_7.setText(QCoreApplication.translate("MainWindow", u"Arrival (hh:mm):", None))
        self.redClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.redDispatch.setText(QCoreApplication.translate("MainWindow", u"Dispatch", None))
        self.arrivalLabel_4.setText(QCoreApplication.translate("MainWindow", u"Red Line Tentative Schedule:", None))
        ___qtablewidgetitem2 = self.redTentSchedule.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Dest.", None));
        ___qtablewidgetitem3 = self.redTentSchedule.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"AT", None));
        self.blockLabel_8.setText(QCoreApplication.translate("MainWindow", u"Arrival (hh:mm):", None))
        self.blockLabel_9.setText(QCoreApplication.translate("MainWindow", u"Destination:", None))
        self.redAddStop.setText(QCoreApplication.translate("MainWindow", u"Add Stop", None))
        self.arrivalLabel_5.setText(QCoreApplication.translate("MainWindow", u"Green Line Scheduled Trains:", None))
        self.arrivalLabel_6.setText(QCoreApplication.translate("MainWindow", u"Red Line Scheduled Trains:", None))
        ___qtablewidgetitem4 = self.greenScheduledTrains.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem5 = self.greenScheduledTrains.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Dest.", None));
        ___qtablewidgetitem6 = self.greenScheduledTrains.horizontalHeaderItem(2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"AT", None));
        ___qtablewidgetitem7 = self.greenScheduledTrains.horizontalHeaderItem(3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"DT", None));
        ___qtablewidgetitem8 = self.redScheduledTrains.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Dest.", None));
        ___qtablewidgetitem9 = self.redScheduledTrains.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"AT", None));
        ___qtablewidgetitem10 = self.redScheduledTrains.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"DT", None));
        self.blockLabel_5.setText(QCoreApplication.translate("MainWindow", u"Red Line", None))
        self.red_text_H4.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.green_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.green_M1.setText(QCoreApplication.translate("MainWindow", u"76-77", None))
        self.green_M2.setText(QCoreApplication.translate("MainWindow", u"77-101", None))
        self.red_C1.setText(QCoreApplication.translate("MainWindow", u"9-10", None))
        self.red_H2_2.setText(QCoreApplication.translate("MainWindow", u"32-72", None))
        self.red_H3_1.setText(QCoreApplication.translate("MainWindow", u"38-39", None))
        self.green_text_N.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.red_H1_1.setText(QCoreApplication.translate("MainWindow", u"27-28", None))
        self.green_N2.setText(QCoreApplication.translate("MainWindow", u"85-100", None))
        self.red_H4_1.setText(QCoreApplication.translate("MainWindow", u"43-44", None))
        self.red_J1.setText(QCoreApplication.translate("MainWindow", u"52-53", None))
        self.red_text_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.green_text_G.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.green_J1_1.setText(QCoreApplication.translate("MainWindow", u"57-Yard", None))
        self.green_text_J2.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.red_H1_2.setText(QCoreApplication.translate("MainWindow", u"27-76", None))
        self.red_text_H1.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH3.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH2.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_H2_1.setText(QCoreApplication.translate("MainWindow", u"32-33", None))
        self.green_G1.setText(QCoreApplication.translate("MainWindow", u"29-30", None))
        self.red_E2.setText(QCoreApplication.translate("MainWindow", u"1-16", None))
        self.green_J2_1.setText(QCoreApplication.translate("MainWindow", u"62-63", None))
        self.red_J2.setText(QCoreApplication.translate("MainWindow", u"52-66", None))
        self.red_text_J.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.red_C2.setText(QCoreApplication.translate("MainWindow", u"9-Yard", None))
        self.red_H4_2.setText(QCoreApplication.translate("MainWindow", u"43-67", None))
        self.green_J1_2.setText(QCoreApplication.translate("MainWindow", u"57-58", None))
        self.red_E1.setText(QCoreApplication.translate("MainWindow", u"15-16", None))
        self.red_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.green_G2.setText(QCoreApplication.translate("MainWindow", u"29-150", None))
        self.green_N1.setText(QCoreApplication.translate("MainWindow", u"85-86", None))
        self.green_text_J1.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.green_J2_2.setText(QCoreApplication.translate("MainWindow", u"Yard-63", None))
        self.red_H3_2.setText(QCoreApplication.translate("MainWindow", u"38-71", None))
        self.green_text_M.setText(QCoreApplication.translate("MainWindow", u"M", None))
        self.blockLabel_4.setText(QCoreApplication.translate("MainWindow", u"Green Line", None))
        self.green_C2.setText(QCoreApplication.translate("MainWindow", u"1-13", None))
        self.green_C1.setText(QCoreApplication.translate("MainWindow", u"12-13", None))
        self.legendLabel_2.setText(QCoreApplication.translate("MainWindow", u"- Occupied by train", None))
        self.modesText.setText(QCoreApplication.translate("MainWindow", u"Modes:", None))
        self.time10x.setText(QCoreApplication.translate("MainWindow", u"10x", None))
        self.dataTime.setText(QCoreApplication.translate("MainWindow", u"07:00:00", None))
        self.dispatchGreen.setText(QCoreApplication.translate("MainWindow", u"Green Line", None))
        self.optionsLabel.setText(QCoreApplication.translate("MainWindow", u"Track Block Options", None))
        self.legendLabel_4.setText(QCoreApplication.translate("MainWindow", u"- Block under \n"
"   maintenance", None))
        self.label_2.setText("")
        self.dispatchRed.setText(QCoreApplication.translate("MainWindow", u"Red Line", None))
        self.maintenanceSelect.setText(QCoreApplication.translate("MainWindow", u"Maintenance", None))
        self.autoSelect.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.optionsLabel_3.setText(QCoreApplication.translate("MainWindow", u"Red Line Train Info", None))
        self.manualSelect.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.modeSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"Open", None))
        self.modeSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"Maintenance", None))

        self.xButton.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.lineLabel.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        ___qtablewidgetitem11 = self.redOccupancy.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Occupied", None));
        ___qtablewidgetitem12 = self.redOccupancy.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Infrastructure", None));
        ___qtablewidgetitem13 = self.redOccupancy.horizontalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Block Status", None));
        ___qtablewidgetitem14 = self.greenOccupancy.horizontalHeaderItem(0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Occupied", None));
        ___qtablewidgetitem15 = self.greenOccupancy.horizontalHeaderItem(1)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Infrastructure", None));
        ___qtablewidgetitem16 = self.greenOccupancy.horizontalHeaderItem(2)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Block Status", None));
        self.time50x.setText(QCoreApplication.translate("MainWindow", u"50x", None))
        self.timePause.setText(QCoreApplication.translate("MainWindow", u"| |", None))
        self.greenOccupancyText.setText(QCoreApplication.translate("MainWindow", u"          Green Line Occupancy", None))
        self.redOccupancyText.setText(QCoreApplication.translate("MainWindow", u"             Red Line Occupancy", None))
        self.thisIsATest.setText(QCoreApplication.translate("MainWindow", u"send a train", None))
        ___qtablewidgetitem17 = self.greenTrainInfoTable.horizontalHeaderItem(0)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Train Tag", None));
        ___qtablewidgetitem18 = self.greenTrainInfoTable.horizontalHeaderItem(1)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"Current Block", None));
        ___qtablewidgetitem19 = self.greenTrainInfoTable.horizontalHeaderItem(2)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Authority", None));
        ___qtablewidgetitem20 = self.greenTrainInfoTable.horizontalHeaderItem(3)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"Next Destination", None));
        ___qtablewidgetitem21 = self.redTrainInfoTable.horizontalHeaderItem(0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"Train Tag", None));
        ___qtablewidgetitem22 = self.redTrainInfoTable.horizontalHeaderItem(1)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"Current Block", None));
        ___qtablewidgetitem23 = self.redTrainInfoTable.horizontalHeaderItem(2)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"Authority", None));
        ___qtablewidgetitem24 = self.redTrainInfoTable.horizontalHeaderItem(3)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Next Destination", None));
        self.blockLabel_10.setText(QCoreApplication.translate("MainWindow", u"Throughput (per hour):", None))
        self.blockLabel_11.setText(QCoreApplication.translate("MainWindow", u"Green Line:", None))
        self.blockLabel_12.setText(QCoreApplication.translate("MainWindow", u"Red Line:", None))
        self.redThroughput.setText(QCoreApplication.translate("MainWindow", u"- passengers", None))
        self.greenThroughput.setText(QCoreApplication.translate("MainWindow", u"- passengers", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"testbutton", None))
        self.menuNorth_Shore_Extension_CTC_Window.setTitle(QCoreApplication.translate("MainWindow", u"North Shore Extension - CTC Window", None))
    # retranslateUi

