# Form implementation generated from reading ui file 'trainModel_fullsys.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 527)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trainBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.trainBox.setGeometry(QtCore.QRect(20, 65, 191, 31))
        self.trainBox.setObjectName("trainBox")
        self.powProgressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.powProgressBar.setGeometry(QtCore.QRect(260, 290, 251, 23))
        self.powProgressBar.setStyleSheet("QProgressBar {\n"
"     border: 2px solid black;\n"
"     border-radius: 5px;\n"
"     background-color: white;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: yellow;\n"
"     width: 20px;\n"
" }")
        self.powProgressBar.setProperty("value", 24)
        self.powProgressBar.setObjectName("powProgressBar")
        self.ACprogressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.ACprogressBar.setGeometry(QtCore.QRect(10, 320, 151, 21))
        self.ACprogressBar.setStyleSheet("QProgressBar {\n"
"     border: 2px solid black;\n"
"     border-radius: 5px;\n"
"     background-color: white;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: blue;\n"
"     width: 20px;\n"
" }")
        self.ACprogressBar.setProperty("value", 24)
        self.ACprogressBar.setObjectName("ACprogressBar")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 380, 121, 21))
        self.label_12.setStyleSheet("font: 15pt \"Segoe UI\";")
        self.label_12.setObjectName("label_12")
        self.errorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(130, 290, 31, 31))
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.actSpeed = QtWidgets.QLabel(parent=self.centralwidget)
        self.actSpeed.setGeometry(QtCore.QRect(260, 130, 251, 71))
        self.actSpeed.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.actSpeed.setObjectName("actSpeed")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.label_22.setObjectName("label_22")
        self.powLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.powLabel.setGeometry(QtCore.QRect(260, 310, 251, 41))
        self.powLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.powLabel.setObjectName("powLabel")
        self.lDoorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.lDoorLabel.setGeometry(QtCore.QRect(166, 220, 51, 20))
        self.lDoorLabel.setObjectName("lDoorLabel")
        self.sigFaultLabel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sigFaultLabel.setGeometry(QtCore.QRect(10, 400, 71, 61))
        self.sigFaultLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.sigFaultLabel.setText("")
        self.sigFaultLabel.setObjectName("sigFaultLabel")
        self.EmerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EmerButton.setGeometry(QtCore.QRect(540, 220, 241, 191))
        self.EmerButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.EmerButton.setObjectName("EmerButton")
        self.tempLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.tempLabel.setGeometry(QtCore.QRect(10, 340, 211, 31))
        self.tempLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;\n"
"font: 11pt \"Segoe UI\";")
        self.tempLabel.setObjectName("tempLabel")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 100, 111, 191))
        self.label_23.setObjectName("label_23")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 300, 111, 20))
        self.label.setObjectName("label")
        self.commSpeedLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.commSpeedLabel.setGeometry(QtCore.QRect(260, 200, 251, 31))
        self.commSpeedLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.commSpeedLabel.setObjectName("commSpeedLabel")
        self.ACIcon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ACIcon.setGeometry(QtCore.QRect(170, 280, 51, 51))
        self.ACIcon.setStyleSheet("color: rgb(255, 255, 255);")
        self.ACIcon.setText("")
        self.ACIcon.setObjectName("ACIcon")
        self.headlightLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.headlightLabel.setGeometry(QtCore.QRect(166, 190, 51, 20))
        self.headlightLabel.setObjectName("headlightLabel")
        self.brakeFaultLabel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.brakeFaultLabel.setGeometry(QtCore.QRect(150, 400, 71, 61))
        self.brakeFaultLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.brakeFaultLabel.setText("")
        self.brakeFaultLabel.setObjectName("brakeFaultLabel")
        self.extLightLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.extLightLabel.setGeometry(QtCore.QRect(166, 160, 51, 20))
        self.extLightLabel.setObjectName("extLightLabel")
        self.rDoorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.rDoorLabel.setGeometry(QtCore.QRect(166, 250, 51, 20))
        self.rDoorLabel.setObjectName("rDoorLabel")
        self.currentFile = QtWidgets.QLabel(parent=self.centralwidget)
        self.currentFile.setGeometry(QtCore.QRect(540, 440, 231, 20))
        self.currentFile.setObjectName("currentFile")
        self.powFaultLabel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.powFaultLabel.setGeometry(QtCore.QRect(80, 400, 71, 61))
        self.powFaultLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.powFaultLabel.setText("")
        self.powFaultLabel.setObjectName("powFaultLabel")
        self.tempLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.tempLabel_2.setGeometry(QtCore.QRect(260, 380, 251, 41))
        self.tempLabel_2.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;\n"
"font: 11pt \"Segoe UI\";")
        self.tempLabel_2.setObjectName("tempLabel_2")
        self.speedLimitLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.speedLimitLabel.setGeometry(QtCore.QRect(260, 230, 251, 31))
        self.speedLimitLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.speedLimitLabel.setObjectName("speedLimitLabel")
        self.dateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(580, 40, 191, 31))
        self.dateLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.intLightLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.intLightLabel.setGeometry(QtCore.QRect(166, 130, 51, 20))
        self.intLightLabel.setObjectName("intLightLabel")
        self.greenLineButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.greenLineButton.setGeometry(QtCore.QRect(390, 40, 121, 51))
        self.greenLineButton.setStyleSheet("")
        self.greenLineButton.setObjectName("greenLineButton")
        self.redLineButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.redLineButton.setGeometry(QtCore.QRect(260, 40, 121, 51))
        self.redLineButton.setObjectName("redLineButton")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(540, 90, 231, 101))
        self.label_17.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.label_17.setObjectName("label_17")
        self.currBlockLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.currBlockLabel.setGeometry(QtCore.QRect(260, 420, 251, 41))
        self.currBlockLabel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 2px;\n"
"font: 11pt \"Segoe UI\";")
        self.currBlockLabel.setObjectName("currBlockLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "Fault Status"))
        self.actSpeed.setText(_translate("MainWindow", "Current Speed:"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Current Train:</span></p></body></html>"))
        self.powLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Power Input:</span></p></body></html>"))
        self.lDoorLabel.setText(_translate("MainWindow", "Null"))
        self.EmerButton.setText(_translate("MainWindow", "EMERGENCY BRAKE"))
        self.tempLabel.setText(_translate("MainWindow", "Internal Temp:"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Internal Lights:</span></p><p><span style=\" font-size:12pt;\">External Lights:</span></p><p><span style=\" font-size:12pt;\">Headlights:</span></p><p><span style=\" font-size:12pt;\">Left Doors:</span></p><p><span style=\" font-size:12pt;\">Right Doors:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Min: 60  Max: 90"))
        self.commSpeedLabel.setText(_translate("MainWindow", "Commanded Speed:"))
        self.headlightLabel.setText(_translate("MainWindow", "Null"))
        self.extLightLabel.setText(_translate("MainWindow", "Null"))
        self.rDoorLabel.setText(_translate("MainWindow", "Null"))
        self.currentFile.setText(_translate("MainWindow", "Current Schedule:"))
        self.tempLabel_2.setText(_translate("MainWindow", "Current Section:"))
        self.speedLimitLabel.setText(_translate("MainWindow", "Speed Limit:"))
        self.intLightLabel.setText(_translate("MainWindow", "Null"))
        self.greenLineButton.setText(_translate("MainWindow", "GREEN LINE"))
        self.redLineButton.setText(_translate("MainWindow", "RED LINE"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Destination:</p><p><br/></p></body></html>"))
        self.currBlockLabel.setText(_translate("MainWindow", "Current Block:"))
