# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ctcUI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStackedWidget, QStatusBar, QTableWidget,
    QTableWidgetItem, QTimeEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1663, 615)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scheduledTrains = QCheckBox(self.centralwidget)
        self.scheduledTrains.setObjectName(u"scheduledTrains")
        self.scheduledTrains.setGeometry(QRect(160, 70, 111, 22))
        self.legendLabel_3 = QLabel(self.centralwidget)
        self.legendLabel_3.setObjectName(u"legendLabel_3")
        self.legendLabel_3.setGeometry(QRect(540, 370, 101, 16))
        self.legendLabel = QLabel(self.centralwidget)
        self.legendLabel.setObjectName(u"legendLabel")
        self.legendLabel.setGeometry(QRect(520, 320, 101, 16))
        self.checkButton = QPushButton(self.centralwidget)
        self.checkButton.setObjectName(u"checkButton")
        self.checkButton.setGeometry(QRect(430, 420, 31, 24))
        self.blockSelectMaintenance = QComboBox(self.centralwidget)
        self.blockSelectMaintenance.setObjectName(u"blockSelectMaintenance")
        self.blockSelectMaintenance.setGeometry(QRect(410, 360, 51, 21))
        self.time1x = QPushButton(self.centralwidget)
        self.time1x.setObjectName(u"time1x")
        self.time1x.setGeometry(QRect(400, 490, 31, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(510, 340, 21, 16))
        self.label.setStyleSheet(u"background-color: green\n"
"")
        self.Outline2_2 = QFrame(self.centralwidget)
        self.Outline2_2.setObjectName(u"Outline2_2")
        self.Outline2_2.setGeometry(QRect(310, 40, 151, 21))
        self.Outline2_2.setAutoFillBackground(False)
        self.Outline2_2.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2_2.setFrameShape(QFrame.StyledPanel)
        self.Outline2_2.setFrameShadow(QFrame.Raised)
        self.optionsLabel_2 = QLabel(self.Outline2_2)
        self.optionsLabel_2.setObjectName(u"optionsLabel_2")
        self.optionsLabel_2.setGeometry(QRect(20, 1, 121, 16))
        font = QFont()
        font.setPointSize(10)
        self.optionsLabel_2.setFont(font)
        self.optionsLabel_2.setStyleSheet(u"color: black")
        self.uploadSchedule = QPushButton(self.centralwidget)
        self.uploadSchedule.setObjectName(u"uploadSchedule")
        self.uploadSchedule.setGeometry(QRect(440, 490, 101, 24))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(510, 400, 21, 16))
        self.label_3.setStyleSheet(u"background-color: Gold\n"
"")
        self.Outline = QFrame(self.centralwidget)
        self.Outline.setObjectName(u"Outline")
        self.Outline.setGeometry(QRect(10, 10, 281, 51))
        self.Outline.setAutoFillBackground(False)
        self.Outline.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline.setFrameShape(QFrame.StyledPanel)
        self.Outline.setFrameShadow(QFrame.Raised)
        self.DispatchTrain = QLabel(self.Outline)
        self.DispatchTrain.setObjectName(u"DispatchTrain")
        self.DispatchTrain.setGeometry(QRect(80, 10, 141, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.DispatchTrain.setFont(font1)
        self.DispatchTrain.setStyleSheet(u"color: black")
        self.blockLabel_2 = QLabel(self.centralwidget)
        self.blockLabel_2.setObjectName(u"blockLabel_2")
        self.blockLabel_2.setGeometry(QRect(420, 340, 31, 16))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(500, 310, 151, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 100, 281, 441))
        self.greenLinePage = QWidget()
        self.greenLinePage.setObjectName(u"greenLinePage")
        self.dormontStation = QPushButton(self.greenLinePage)
        self.dormontStation.setObjectName(u"dormontStation")
        self.dormontStation.setGeometry(QRect(0, 240, 91, 24))
        self.glenburyStation = QPushButton(self.greenLinePage)
        self.glenburyStation.setObjectName(u"glenburyStation")
        self.glenburyStation.setGeometry(QRect(0, 210, 91, 24))
        self.edgebrookStation = QPushButton(self.greenLinePage)
        self.edgebrookStation.setObjectName(u"edgebrookStation")
        self.edgebrookStation.setGeometry(QRect(0, 30, 91, 24))
        self.pioneerStation = QPushButton(self.greenLinePage)
        self.pioneerStation.setObjectName(u"pioneerStation")
        self.pioneerStation.setGeometry(QRect(0, 0, 91, 24))
        self.overbrookStation = QPushButton(self.greenLinePage)
        self.overbrookStation.setObjectName(u"overbrookStation")
        self.overbrookStation.setGeometry(QRect(0, 180, 91, 24))
        self.poplarStation = QPushButton(self.greenLinePage)
        self.poplarStation.setObjectName(u"poplarStation")
        self.poplarStation.setGeometry(QRect(0, 300, 91, 24))
        self.castleShannonStation = QPushButton(self.greenLinePage)
        self.castleShannonStation.setObjectName(u"castleShannonStation")
        self.castleShannonStation.setGeometry(QRect(0, 330, 91, 21))
        self.centralStation = QPushButton(self.greenLinePage)
        self.centralStation.setObjectName(u"centralStation")
        self.centralStation.setGeometry(QRect(0, 120, 91, 24))
        self.inglewoodStation = QPushButton(self.greenLinePage)
        self.inglewoodStation.setObjectName(u"inglewoodStation")
        self.inglewoodStation.setGeometry(QRect(0, 150, 91, 24))
        self.southBankStation = QPushButton(self.greenLinePage)
        self.southBankStation.setObjectName(u"southBankStation")
        self.southBankStation.setGeometry(QRect(0, 90, 91, 24))
        self.whitedStation = QPushButton(self.greenLinePage)
        self.whitedStation.setObjectName(u"whitedStation")
        self.whitedStation.setGeometry(QRect(0, 60, 91, 24))
        self.lebanonStation = QPushButton(self.greenLinePage)
        self.lebanonStation.setObjectName(u"lebanonStation")
        self.lebanonStation.setGeometry(QRect(0, 270, 91, 24))
        self.greenBlockDispatch = QComboBox(self.greenLinePage)
        self.greenBlockDispatch.addItem("")
        self.greenBlockDispatch.setObjectName(u"greenBlockDispatch")
        self.greenBlockDispatch.setGeometry(QRect(200, 10, 51, 21))
        self.blockLabel = QLabel(self.greenLinePage)
        self.blockLabel.setObjectName(u"blockLabel")
        self.blockLabel.setGeometry(QRect(110, 10, 81, 21))
        self.greenAddStation = QPushButton(self.greenLinePage)
        self.greenAddStation.setObjectName(u"greenAddStation")
        self.greenAddStation.setGeometry(QRect(10, 360, 71, 21))
        self.greenAddStation.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.greenAddBlock = QPushButton(self.greenLinePage)
        self.greenAddBlock.setObjectName(u"greenAddBlock")
        self.greenAddBlock.setGeometry(QRect(150, 40, 71, 21))
        self.greenAddBlock.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.greenTentSchedule = QListWidget(self.greenLinePage)
        self.greenTentSchedule.setObjectName(u"greenTentSchedule")
        self.greenTentSchedule.setGeometry(QRect(110, 170, 151, 181))
        self.arrivalLabel = QLabel(self.greenLinePage)
        self.arrivalLabel.setObjectName(u"arrivalLabel")
        self.arrivalLabel.setGeometry(QRect(110, 120, 71, 21))
        self.greenArrivalInput = QTimeEdit(self.greenLinePage)
        self.greenArrivalInput.setObjectName(u"greenArrivalInput")
        self.greenArrivalInput.setGeometry(QRect(190, 120, 71, 20))
        self.greenClear = QPushButton(self.greenLinePage)
        self.greenClear.setObjectName(u"greenClear")
        self.greenClear.setGeometry(QRect(120, 360, 61, 21))
        self.greenClear.setStyleSheet(u"background-color: Red; color: Black")
        self.greenDispatch = QPushButton(self.greenLinePage)
        self.greenDispatch.setObjectName(u"greenDispatch")
        self.greenDispatch.setGeometry(QRect(190, 360, 61, 21))
        self.greenDispatch.setStyleSheet(u"background-color: Green; color: Black")
        self.arrivalLabel_3 = QLabel(self.greenLinePage)
        self.arrivalLabel_3.setObjectName(u"arrivalLabel_3")
        self.arrivalLabel_3.setGeometry(QRect(110, 151, 111, 20))
        self.stackedWidget.addWidget(self.greenLinePage)
        self.redLinePage = QWidget()
        self.redLinePage.setObjectName(u"redLinePage")
        self.redArrivalInput = QTimeEdit(self.redLinePage)
        self.redArrivalInput.setObjectName(u"redArrivalInput")
        self.redArrivalInput.setGeometry(QRect(190, 120, 71, 20))
        self.blockLabel_3 = QLabel(self.redLinePage)
        self.blockLabel_3.setObjectName(u"blockLabel_3")
        self.blockLabel_3.setGeometry(QRect(110, 10, 81, 21))
        self.redAddBlock = QPushButton(self.redLinePage)
        self.redAddBlock.setObjectName(u"redAddBlock")
        self.redAddBlock.setGeometry(QRect(150, 40, 71, 21))
        self.redAddBlock.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.redTentSchedule = QListWidget(self.redLinePage)
        self.redTentSchedule.setObjectName(u"redTentSchedule")
        self.redTentSchedule.setGeometry(QRect(110, 170, 151, 181))
        self.arrivalLabel_2 = QLabel(self.redLinePage)
        self.arrivalLabel_2.setObjectName(u"arrivalLabel_2")
        self.arrivalLabel_2.setGeometry(QRect(110, 120, 71, 21))
        self.redBlockDispatch = QComboBox(self.redLinePage)
        self.redBlockDispatch.addItem("")
        self.redBlockDispatch.setObjectName(u"redBlockDispatch")
        self.redBlockDispatch.setGeometry(QRect(200, 10, 51, 21))
        self.redAddStation = QPushButton(self.redLinePage)
        self.redAddStation.setObjectName(u"redAddStation")
        self.redAddStation.setGeometry(QRect(10, 240, 71, 21))
        self.redAddStation.setStyleSheet(u"background-color: DodgerBlue; color: Black")
        self.southHillsStation = QPushButton(self.redLinePage)
        self.southHillsStation.setObjectName(u"southHillsStation")
        self.southHillsStation.setGeometry(QRect(0, 210, 91, 21))
        self.herronStation = QPushButton(self.redLinePage)
        self.herronStation.setObjectName(u"herronStation")
        self.herronStation.setGeometry(QRect(0, 30, 91, 24))
        self.shadysideStation = QPushButton(self.redLinePage)
        self.shadysideStation.setObjectName(u"shadysideStation")
        self.shadysideStation.setGeometry(QRect(0, 0, 91, 24))
        self.staionSquareStation = QPushButton(self.redLinePage)
        self.staionSquareStation.setObjectName(u"staionSquareStation")
        self.staionSquareStation.setGeometry(QRect(0, 180, 91, 24))
        self.steelPlazaStaion = QPushButton(self.redLinePage)
        self.steelPlazaStaion.setObjectName(u"steelPlazaStaion")
        self.steelPlazaStaion.setGeometry(QRect(0, 120, 91, 24))
        self.firstAveStation = QPushButton(self.redLinePage)
        self.firstAveStation.setObjectName(u"firstAveStation")
        self.firstAveStation.setGeometry(QRect(0, 150, 91, 24))
        self.pennStation = QPushButton(self.redLinePage)
        self.pennStation.setObjectName(u"pennStation")
        self.pennStation.setGeometry(QRect(0, 90, 91, 24))
        self.swissvilleStation = QPushButton(self.redLinePage)
        self.swissvilleStation.setObjectName(u"swissvilleStation")
        self.swissvilleStation.setGeometry(QRect(0, 60, 91, 24))
        self.redClear = QPushButton(self.redLinePage)
        self.redClear.setObjectName(u"redClear")
        self.redClear.setGeometry(QRect(120, 360, 61, 21))
        self.redClear.setStyleSheet(u"background-color: Red; color: Black")
        self.redDispatch = QPushButton(self.redLinePage)
        self.redDispatch.setObjectName(u"redDispatch")
        self.redDispatch.setGeometry(QRect(190, 360, 61, 21))
        self.redDispatch.setStyleSheet(u"background-color: Green; color: Black")
        self.arrivalLabel_4 = QLabel(self.redLinePage)
        self.arrivalLabel_4.setObjectName(u"arrivalLabel_4")
        self.arrivalLabel_4.setGeometry(QRect(110, 151, 111, 20))
        self.stackedWidget.addWidget(self.redLinePage)
        self.scheduledPage = QWidget()
        self.scheduledPage.setObjectName(u"scheduledPage")
        self.greenScheduledTrains = QListWidget(self.scheduledPage)
        self.greenScheduledTrains.setObjectName(u"greenScheduledTrains")
        self.greenScheduledTrains.setGeometry(QRect(0, 20, 281, 171))
        self.redTentSchedule_3 = QListWidget(self.scheduledPage)
        self.redTentSchedule_3.setObjectName(u"redTentSchedule_3")
        self.redTentSchedule_3.setGeometry(QRect(0, 230, 281, 171))
        self.arrivalLabel_5 = QLabel(self.scheduledPage)
        self.arrivalLabel_5.setObjectName(u"arrivalLabel_5")
        self.arrivalLabel_5.setGeometry(QRect(0, 0, 161, 20))
        self.arrivalLabel_6 = QLabel(self.scheduledPage)
        self.arrivalLabel_6.setObjectName(u"arrivalLabel_6")
        self.arrivalLabel_6.setGeometry(QRect(0, 210, 141, 20))
        self.stackedWidget.addWidget(self.scheduledPage)
        self.trackSwitchStates = QWidget()
        self.trackSwitchStates.setObjectName(u"trackSwitchStates")
        self.blockLabel_5 = QLabel(self.trackSwitchStates)
        self.blockLabel_5.setObjectName(u"blockLabel_5")
        self.blockLabel_5.setGeometry(QRect(120, 200, 51, 21))
        self.red_text_H4 = QLabel(self.trackSwitchStates)
        self.red_text_H4.setObjectName(u"red_text_H4")
        self.red_text_H4.setGeometry(QRect(30, 370, 16, 16))
        self.green_text_C = QLabel(self.trackSwitchStates)
        self.green_text_C.setObjectName(u"green_text_C")
        self.green_text_C.setGeometry(QRect(30, 20, 16, 16))
        self.green_M1 = QPushButton(self.trackSwitchStates)
        self.green_M1.setObjectName(u"green_M1")
        self.green_M1.setGeometry(QRect(70, 140, 80, 24))
        self.green_M2 = QPushButton(self.trackSwitchStates)
        self.green_M2.setObjectName(u"green_M2")
        self.green_M2.setGeometry(QRect(150, 140, 80, 24))
        self.red_C1 = QPushButton(self.trackSwitchStates)
        self.red_C1.setObjectName(u"red_C1")
        self.red_C1.setGeometry(QRect(70, 220, 80, 24))
        self.red_H2_2 = QPushButton(self.trackSwitchStates)
        self.red_H2_2.setObjectName(u"red_H2_2")
        self.red_H2_2.setGeometry(QRect(150, 310, 80, 24))
        self.red_H3_1 = QPushButton(self.trackSwitchStates)
        self.red_H3_1.setObjectName(u"red_H3_1")
        self.red_H3_1.setGeometry(QRect(70, 340, 80, 24))
        self.green_text_N = QLabel(self.trackSwitchStates)
        self.green_text_N.setObjectName(u"green_text_N")
        self.green_text_N.setGeometry(QRect(30, 170, 16, 16))
        self.red_H1_1 = QPushButton(self.trackSwitchStates)
        self.red_H1_1.setObjectName(u"red_H1_1")
        self.red_H1_1.setGeometry(QRect(70, 280, 80, 24))
        self.green_N2 = QPushButton(self.trackSwitchStates)
        self.green_N2.setObjectName(u"green_N2")
        self.green_N2.setGeometry(QRect(150, 170, 80, 24))
        self.red_H4_1 = QPushButton(self.trackSwitchStates)
        self.red_H4_1.setObjectName(u"red_H4_1")
        self.red_H4_1.setGeometry(QRect(70, 370, 80, 24))
        self.red_J1 = QPushButton(self.trackSwitchStates)
        self.red_J1.setObjectName(u"red_J1")
        self.red_J1.setGeometry(QRect(70, 400, 80, 24))
        self.red_text_E = QLabel(self.trackSwitchStates)
        self.red_text_E.setObjectName(u"red_text_E")
        self.red_text_E.setGeometry(QRect(30, 250, 16, 16))
        self.green_text_G = QLabel(self.trackSwitchStates)
        self.green_text_G.setObjectName(u"green_text_G")
        self.green_text_G.setGeometry(QRect(30, 50, 16, 16))
        self.green_J1_1 = QPushButton(self.trackSwitchStates)
        self.green_J1_1.setObjectName(u"green_J1_1")
        self.green_J1_1.setGeometry(QRect(70, 80, 80, 24))
        self.green_text_J2 = QLabel(self.trackSwitchStates)
        self.green_text_J2.setObjectName(u"green_text_J2")
        self.green_text_J2.setGeometry(QRect(30, 110, 16, 16))
        self.red_H1_2 = QPushButton(self.trackSwitchStates)
        self.red_H1_2.setObjectName(u"red_H1_2")
        self.red_H1_2.setGeometry(QRect(150, 280, 80, 24))
        self.red_text_H1 = QLabel(self.trackSwitchStates)
        self.red_text_H1.setObjectName(u"red_text_H1")
        self.red_text_H1.setGeometry(QRect(30, 280, 16, 16))
        self.red_textH3 = QLabel(self.trackSwitchStates)
        self.red_textH3.setObjectName(u"red_textH3")
        self.red_textH3.setGeometry(QRect(30, 340, 16, 16))
        self.red_textH2 = QLabel(self.trackSwitchStates)
        self.red_textH2.setObjectName(u"red_textH2")
        self.red_textH2.setGeometry(QRect(30, 310, 16, 16))
        self.red_H2_1 = QPushButton(self.trackSwitchStates)
        self.red_H2_1.setObjectName(u"red_H2_1")
        self.red_H2_1.setGeometry(QRect(70, 310, 80, 24))
        self.green_G1 = QPushButton(self.trackSwitchStates)
        self.green_G1.setObjectName(u"green_G1")
        self.green_G1.setGeometry(QRect(70, 50, 80, 24))
        self.red_E2 = QPushButton(self.trackSwitchStates)
        self.red_E2.setObjectName(u"red_E2")
        self.red_E2.setGeometry(QRect(150, 250, 80, 24))
        self.green_J2_1 = QPushButton(self.trackSwitchStates)
        self.green_J2_1.setObjectName(u"green_J2_1")
        self.green_J2_1.setGeometry(QRect(70, 110, 80, 24))
        self.red_J2 = QPushButton(self.trackSwitchStates)
        self.red_J2.setObjectName(u"red_J2")
        self.red_J2.setGeometry(QRect(150, 400, 80, 24))
        self.red_text_J = QLabel(self.trackSwitchStates)
        self.red_text_J.setObjectName(u"red_text_J")
        self.red_text_J.setGeometry(QRect(30, 400, 16, 16))
        self.red_C2 = QPushButton(self.trackSwitchStates)
        self.red_C2.setObjectName(u"red_C2")
        self.red_C2.setGeometry(QRect(150, 220, 80, 24))
        self.red_H4_2 = QPushButton(self.trackSwitchStates)
        self.red_H4_2.setObjectName(u"red_H4_2")
        self.red_H4_2.setGeometry(QRect(150, 370, 80, 24))
        self.green_J1_2 = QPushButton(self.trackSwitchStates)
        self.green_J1_2.setObjectName(u"green_J1_2")
        self.green_J1_2.setGeometry(QRect(150, 80, 80, 24))
        self.red_E1 = QPushButton(self.trackSwitchStates)
        self.red_E1.setObjectName(u"red_E1")
        self.red_E1.setGeometry(QRect(70, 250, 80, 24))
        self.red_text_C = QLabel(self.trackSwitchStates)
        self.red_text_C.setObjectName(u"red_text_C")
        self.red_text_C.setGeometry(QRect(30, 220, 16, 16))
        self.green_G2 = QPushButton(self.trackSwitchStates)
        self.green_G2.setObjectName(u"green_G2")
        self.green_G2.setGeometry(QRect(150, 50, 80, 24))
        self.green_N1 = QPushButton(self.trackSwitchStates)
        self.green_N1.setObjectName(u"green_N1")
        self.green_N1.setGeometry(QRect(70, 170, 80, 24))
        self.green_text_J1 = QLabel(self.trackSwitchStates)
        self.green_text_J1.setObjectName(u"green_text_J1")
        self.green_text_J1.setGeometry(QRect(30, 80, 16, 16))
        self.green_J2_2 = QPushButton(self.trackSwitchStates)
        self.green_J2_2.setObjectName(u"green_J2_2")
        self.green_J2_2.setGeometry(QRect(150, 110, 80, 24))
        self.red_H3_2 = QPushButton(self.trackSwitchStates)
        self.red_H3_2.setObjectName(u"red_H3_2")
        self.red_H3_2.setGeometry(QRect(150, 340, 80, 24))
        self.green_text_M = QLabel(self.trackSwitchStates)
        self.green_text_M.setObjectName(u"green_text_M")
        self.green_text_M.setGeometry(QRect(30, 140, 16, 16))
        self.blockLabel_4 = QLabel(self.trackSwitchStates)
        self.blockLabel_4.setObjectName(u"blockLabel_4")
        self.blockLabel_4.setGeometry(QRect(110, 0, 61, 21))
        self.green_C2 = QPushButton(self.trackSwitchStates)
        self.green_C2.setObjectName(u"green_C2")
        self.green_C2.setGeometry(QRect(150, 20, 80, 24))
        self.green_C1 = QPushButton(self.trackSwitchStates)
        self.green_C1.setObjectName(u"green_C1")
        self.green_C1.setGeometry(QRect(70, 20, 80, 24))
        self.stackedWidget.addWidget(self.trackSwitchStates)
        self.legendLabel_2 = QLabel(self.centralwidget)
        self.legendLabel_2.setObjectName(u"legendLabel_2")
        self.legendLabel_2.setGeometry(QRect(540, 340, 101, 16))
        self.modesText = QLabel(self.centralwidget)
        self.modesText.setObjectName(u"modesText")
        self.modesText.setGeometry(QRect(550, 490, 41, 21))
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(500, 430, 151, 21))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.time10x = QPushButton(self.centralwidget)
        self.time10x.setObjectName(u"time10x")
        self.time10x.setGeometry(QRect(370, 510, 31, 21))
        self.dataTime = QLabel(self.centralwidget)
        self.dataTime.setObjectName(u"dataTime")
        self.dataTime.setGeometry(QRect(320, 490, 51, 16))
        self.dispatchGreen = QCheckBox(self.centralwidget)
        self.dispatchGreen.setObjectName(u"dispatchGreen")
        self.dispatchGreen.setGeometry(QRect(10, 70, 78, 22))
        self.Outline2 = QFrame(self.centralwidget)
        self.Outline2.setObjectName(u"Outline2")
        self.Outline2.setGeometry(QRect(310, 320, 151, 21))
        self.Outline2.setAutoFillBackground(False)
        self.Outline2.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2.setFrameShape(QFrame.StyledPanel)
        self.Outline2.setFrameShadow(QFrame.Raised)
        self.optionsLabel = QLabel(self.Outline2)
        self.optionsLabel.setObjectName(u"optionsLabel")
        self.optionsLabel.setGeometry(QRect(20, 1, 121, 16))
        self.optionsLabel.setFont(font)
        self.optionsLabel.setStyleSheet(u"color: black")
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(640, 320, 20, 121))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.legendLabel_4 = QLabel(self.centralwidget)
        self.legendLabel_4.setObjectName(u"legendLabel_4")
        self.legendLabel_4.setGeometry(QRect(540, 400, 81, 31))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(510, 370, 21, 16))
        self.label_2.setStyleSheet(u"background-color: red\n"
"")
        self.dispatchRed = QCheckBox(self.centralwidget)
        self.dispatchRed.setObjectName(u"dispatchRed")
        self.dispatchRed.setGeometry(QRect(90, 70, 71, 22))
        self.maintenanceSelect = QCheckBox(self.centralwidget)
        self.maintenanceSelect.setObjectName(u"maintenanceSelect")
        self.maintenanceSelect.setGeometry(QRect(750, 490, 91, 22))
        self.autoSelect = QCheckBox(self.centralwidget)
        self.autoSelect.setObjectName(u"autoSelect")
        self.autoSelect.setGeometry(QRect(600, 490, 78, 22))
        self.Outline2_3 = QFrame(self.centralwidget)
        self.Outline2_3.setObjectName(u"Outline2_3")
        self.Outline2_3.setGeometry(QRect(310, 170, 151, 21))
        self.Outline2_3.setAutoFillBackground(False)
        self.Outline2_3.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.Outline2_3.setFrameShape(QFrame.StyledPanel)
        self.Outline2_3.setFrameShadow(QFrame.Raised)
        self.optionsLabel_3 = QLabel(self.Outline2_3)
        self.optionsLabel_3.setObjectName(u"optionsLabel_3")
        self.optionsLabel_3.setGeometry(QRect(20, 1, 121, 16))
        self.optionsLabel_3.setFont(font)
        self.optionsLabel_3.setStyleSheet(u"color: black")
        self.lineSelectMaintenance = QComboBox(self.centralwidget)
        self.lineSelectMaintenance.setObjectName(u"lineSelectMaintenance")
        self.lineSelectMaintenance.setGeometry(QRect(310, 360, 71, 21))
        self.manualSelect = QCheckBox(self.centralwidget)
        self.manualSelect.setObjectName(u"manualSelect")
        self.manualSelect.setGeometry(QRect(680, 490, 61, 22))
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(490, 320, 20, 121))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.modeSelect = QComboBox(self.centralwidget)
        self.modeSelect.addItem("")
        self.modeSelect.addItem("")
        self.modeSelect.setObjectName(u"modeSelect")
        self.modeSelect.setGeometry(QRect(310, 390, 151, 21))
        self.xButton = QPushButton(self.centralwidget)
        self.xButton.setObjectName(u"xButton")
        self.xButton.setGeometry(QRect(390, 420, 31, 24))
        self.lineLabel = QLabel(self.centralwidget)
        self.lineLabel.setObjectName(u"lineLabel")
        self.lineLabel.setGeometry(QRect(330, 340, 31, 16))
        self.redOccupancy = QTableWidget(self.centralwidget)
        if (self.redOccupancy.columnCount() < 3):
            self.redOccupancy.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.redOccupancy.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.redOccupancy.setObjectName(u"redOccupancy")
        self.redOccupancy.setGeometry(QRect(1250, 60, 401, 501))
        self.greenOccupancy = QTableWidget(self.centralwidget)
        if (self.greenOccupancy.columnCount() < 3):
            self.greenOccupancy.setColumnCount(3)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.greenOccupancy.setHorizontalHeaderItem(2, __qtablewidgetitem5)
        self.greenOccupancy.setObjectName(u"greenOccupancy")
        self.greenOccupancy.setGeometry(QRect(850, 60, 401, 501))
        self.time50x = QPushButton(self.centralwidget)
        self.time50x.setObjectName(u"time50x")
        self.time50x.setGeometry(QRect(400, 510, 31, 21))
        self.timePause = QPushButton(self.centralwidget)
        self.timePause.setObjectName(u"timePause")
        self.timePause.setGeometry(QRect(370, 490, 31, 21))
        self.greenOccupancyText = QLabel(self.centralwidget)
        self.greenOccupancyText.setObjectName(u"greenOccupancyText")
        self.greenOccupancyText.setGeometry(QRect(950, 10, 181, 41))
        self.greenOccupancyText.setStyleSheet(u"background-color: LightGreen; color: Black")
        self.redOccupancyText = QLabel(self.centralwidget)
        self.redOccupancyText.setObjectName(u"redOccupancyText")
        self.redOccupancyText.setGeometry(QRect(1380, 10, 181, 41))
        self.redOccupancyText.setStyleSheet(u"background-color: LightCoral; color: Black")
        self.greenTrainInfoTable = QTableWidget(self.centralwidget)
        if (self.greenTrainInfoTable.columnCount() < 5):
            self.greenTrainInfoTable.setColumnCount(5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.greenTrainInfoTable.setHorizontalHeaderItem(4, __qtablewidgetitem10)
        self.greenTrainInfoTable.setObjectName(u"greenTrainInfoTable")
        self.greenTrainInfoTable.setGeometry(QRect(310, 60, 511, 101))
        self.redTrainInfoTable = QTableWidget(self.centralwidget)
        if (self.redTrainInfoTable.columnCount() < 5):
            self.redTrainInfoTable.setColumnCount(5)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(3, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.redTrainInfoTable.setHorizontalHeaderItem(4, __qtablewidgetitem15)
        self.redTrainInfoTable.setObjectName(u"redTrainInfoTable")
        self.redTrainInfoTable.setGeometry(QRect(310, 190, 511, 101))
        self.dormontDispatch = QPushButton(self.centralwidget)
        self.dormontDispatch.setObjectName(u"dormontDispatch")
        self.dormontDispatch.setGeometry(QRect(670, 320, 141, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1663, 21))
        self.menuNorth_Shore_Extension_CTC_Window = QMenu(self.menubar)
        self.menuNorth_Shore_Extension_CTC_Window.setObjectName(u"menuNorth_Shore_Extension_CTC_Window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuNorth_Shore_Extension_CTC_Window.menuAction())

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.scheduledTrains.setText(QCoreApplication.translate("MainWindow", u"Scheduled Trains", None))
        self.legendLabel_3.setText(QCoreApplication.translate("MainWindow", u"- Train authority", None))
        self.legendLabel.setText(QCoreApplication.translate("MainWindow", u"Occupancy Legend", None))
        self.checkButton.setText(QCoreApplication.translate("MainWindow", u"\u2713", None))
        self.time1x.setText(QCoreApplication.translate("MainWindow", u"1x", None))
        self.label.setText("")
        self.optionsLabel_2.setText(QCoreApplication.translate("MainWindow", u"Green Line Train Info", None))
        self.uploadSchedule.setText(QCoreApplication.translate("MainWindow", u"Upload Schedule", None))
        self.label_3.setText("")
        self.DispatchTrain.setText(QCoreApplication.translate("MainWindow", u"Dispatch Train", None))
        self.blockLabel_2.setText(QCoreApplication.translate("MainWindow", u"Block", None))
        self.dormontStation.setText(QCoreApplication.translate("MainWindow", u"Dormont", None))
        self.glenburyStation.setText(QCoreApplication.translate("MainWindow", u"Glenbury", None))
        self.edgebrookStation.setText(QCoreApplication.translate("MainWindow", u"Edgebrook", None))
        self.pioneerStation.setText(QCoreApplication.translate("MainWindow", u"Pioneer", None))
        self.overbrookStation.setText(QCoreApplication.translate("MainWindow", u"Overbrook", None))
        self.poplarStation.setText(QCoreApplication.translate("MainWindow", u"Poplar", None))
        self.castleShannonStation.setText(QCoreApplication.translate("MainWindow", u"Castle Shannon", None))
        self.centralStation.setText(QCoreApplication.translate("MainWindow", u"Central", None))
        self.inglewoodStation.setText(QCoreApplication.translate("MainWindow", u"Inglewood", None))
        self.southBankStation.setText(QCoreApplication.translate("MainWindow", u"South Bank", None))
        self.whitedStation.setText(QCoreApplication.translate("MainWindow", u"Whited", None))
        self.lebanonStation.setText(QCoreApplication.translate("MainWindow", u"Mt. Lebanon", None))
        self.greenBlockDispatch.setItemText(0, QCoreApplication.translate("MainWindow", u"N/A", None))

        self.blockLabel.setText(QCoreApplication.translate("MainWindow", u"Block Number:", None))
        self.greenAddStation.setText(QCoreApplication.translate("MainWindow", u"Add Station", None))
        self.greenAddBlock.setText(QCoreApplication.translate("MainWindow", u"Add Block", None))
        self.arrivalLabel.setText(QCoreApplication.translate("MainWindow", u"Arrival Time:", None))
        self.greenClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.greenDispatch.setText(QCoreApplication.translate("MainWindow", u"Dispatch", None))
        self.arrivalLabel_3.setText(QCoreApplication.translate("MainWindow", u"Tentative Schedule:", None))
        self.blockLabel_3.setText(QCoreApplication.translate("MainWindow", u"Block Number:", None))
        self.redAddBlock.setText(QCoreApplication.translate("MainWindow", u"Add Block", None))
        self.arrivalLabel_2.setText(QCoreApplication.translate("MainWindow", u"Arrival Time:", None))
        self.redBlockDispatch.setItemText(0, QCoreApplication.translate("MainWindow", u"N/A", None))

        self.redAddStation.setText(QCoreApplication.translate("MainWindow", u"Add Station", None))
        self.southHillsStation.setText(QCoreApplication.translate("MainWindow", u"South Hills", None))
        self.herronStation.setText(QCoreApplication.translate("MainWindow", u"Herron Ave", None))
        self.shadysideStation.setText(QCoreApplication.translate("MainWindow", u"Shadyside", None))
        self.staionSquareStation.setText(QCoreApplication.translate("MainWindow", u"Station Square", None))
        self.steelPlazaStaion.setText(QCoreApplication.translate("MainWindow", u"Steel Plaza", None))
        self.firstAveStation.setText(QCoreApplication.translate("MainWindow", u"First Ave", None))
        self.pennStation.setText(QCoreApplication.translate("MainWindow", u"Penn Station", None))
        self.swissvilleStation.setText(QCoreApplication.translate("MainWindow", u"Swissville", None))
        self.redClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.redDispatch.setText(QCoreApplication.translate("MainWindow", u"Dispatch", None))
        self.arrivalLabel_4.setText(QCoreApplication.translate("MainWindow", u"Tentative Schedule:", None))
        self.arrivalLabel_5.setText(QCoreApplication.translate("MainWindow", u"Green Line Scheduled Trains:", None))
        self.arrivalLabel_6.setText(QCoreApplication.translate("MainWindow", u"Red Line Scheduled Trains:", None))
        self.blockLabel_5.setText(QCoreApplication.translate("MainWindow", u"Red Line", None))
        self.red_text_H4.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.green_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.green_M1.setText(QCoreApplication.translate("MainWindow", u"76-77", None))
        self.green_M2.setText(QCoreApplication.translate("MainWindow", u"77-101", None))
        self.red_C1.setText(QCoreApplication.translate("MainWindow", u"9-10", None))
        self.red_H2_2.setText(QCoreApplication.translate("MainWindow", u"32-72", None))
        self.red_H3_1.setText(QCoreApplication.translate("MainWindow", u"38-39", None))
        self.green_text_N.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.red_H1_1.setText(QCoreApplication.translate("MainWindow", u"27-28", None))
        self.green_N2.setText(QCoreApplication.translate("MainWindow", u"85-100", None))
        self.red_H4_1.setText(QCoreApplication.translate("MainWindow", u"43-44", None))
        self.red_J1.setText(QCoreApplication.translate("MainWindow", u"52-53", None))
        self.red_text_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.green_text_G.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.green_J1_1.setText(QCoreApplication.translate("MainWindow", u"57-Yard", None))
        self.green_text_J2.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.red_H1_2.setText(QCoreApplication.translate("MainWindow", u"27-76", None))
        self.red_text_H1.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH3.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH2.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_H2_1.setText(QCoreApplication.translate("MainWindow", u"32-33", None))
        self.green_G1.setText(QCoreApplication.translate("MainWindow", u"29-30", None))
        self.red_E2.setText(QCoreApplication.translate("MainWindow", u"1-16", None))
        self.green_J2_1.setText(QCoreApplication.translate("MainWindow", u"62-63", None))
        self.red_J2.setText(QCoreApplication.translate("MainWindow", u"52-66", None))
        self.red_text_J.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.red_C2.setText(QCoreApplication.translate("MainWindow", u"9-Yard", None))
        self.red_H4_2.setText(QCoreApplication.translate("MainWindow", u"43-67", None))
        self.green_J1_2.setText(QCoreApplication.translate("MainWindow", u"57-58", None))
        self.red_E1.setText(QCoreApplication.translate("MainWindow", u"15-16", None))
        self.red_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.green_G2.setText(QCoreApplication.translate("MainWindow", u"29-150", None))
        self.green_N1.setText(QCoreApplication.translate("MainWindow", u"85-86", None))
        self.green_text_J1.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.green_J2_2.setText(QCoreApplication.translate("MainWindow", u"Yard-63", None))
        self.red_H3_2.setText(QCoreApplication.translate("MainWindow", u"38-71", None))
        self.green_text_M.setText(QCoreApplication.translate("MainWindow", u"M", None))
        self.blockLabel_4.setText(QCoreApplication.translate("MainWindow", u"Green Line", None))
        self.green_C2.setText(QCoreApplication.translate("MainWindow", u"1-13", None))
        self.green_C1.setText(QCoreApplication.translate("MainWindow", u"12-13", None))
        self.legendLabel_2.setText(QCoreApplication.translate("MainWindow", u"- Occupied by train", None))
        self.modesText.setText(QCoreApplication.translate("MainWindow", u"Modes:", None))
        self.time10x.setText(QCoreApplication.translate("MainWindow", u"10x", None))
        self.dataTime.setText(QCoreApplication.translate("MainWindow", u"00:07:00", None))
        self.dispatchGreen.setText(QCoreApplication.translate("MainWindow", u"Green Line", None))
        self.optionsLabel.setText(QCoreApplication.translate("MainWindow", u"Track Block Options", None))
        self.legendLabel_4.setText(QCoreApplication.translate("MainWindow", u"- Block under \n"
"   maintenance", None))
        self.label_2.setText("")
        self.dispatchRed.setText(QCoreApplication.translate("MainWindow", u"Red Line", None))
        self.maintenanceSelect.setText(QCoreApplication.translate("MainWindow", u"Maintenance", None))
        self.autoSelect.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.optionsLabel_3.setText(QCoreApplication.translate("MainWindow", u"Red Line Train Info", None))
        self.manualSelect.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.modeSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"Open", None))
        self.modeSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"Maintenance", None))

        self.xButton.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.lineLabel.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        ___qtablewidgetitem = self.redOccupancy.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Occupied", None));
        ___qtablewidgetitem1 = self.redOccupancy.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Infrastructure", None));
        ___qtablewidgetitem2 = self.redOccupancy.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Block Status", None));
        ___qtablewidgetitem3 = self.greenOccupancy.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Occupied", None));
        ___qtablewidgetitem4 = self.greenOccupancy.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Infrastructure", None));
        ___qtablewidgetitem5 = self.greenOccupancy.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Block Status", None));
        self.time50x.setText(QCoreApplication.translate("MainWindow", u"50x", None))
        self.timePause.setText(QCoreApplication.translate("MainWindow", u"| |", None))
        self.greenOccupancyText.setText(QCoreApplication.translate("MainWindow", u"          Green Line Occupancy", None))
        self.redOccupancyText.setText(QCoreApplication.translate("MainWindow", u"             Red Line Occupancy", None))
        ___qtablewidgetitem6 = self.greenTrainInfoTable.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Train Tag", None));
        ___qtablewidgetitem7 = self.greenTrainInfoTable.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Current Block", None));
        ___qtablewidgetitem8 = self.greenTrainInfoTable.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Current Speed", None));
        ___qtablewidgetitem9 = self.greenTrainInfoTable.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Authority", None));
        ___qtablewidgetitem10 = self.greenTrainInfoTable.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Next Destination", None));
        ___qtablewidgetitem11 = self.redTrainInfoTable.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Train Tag", None));
        ___qtablewidgetitem12 = self.redTrainInfoTable.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Current Block", None));
        ___qtablewidgetitem13 = self.redTrainInfoTable.horizontalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Current Speed", None));
        ___qtablewidgetitem14 = self.redTrainInfoTable.horizontalHeaderItem(3)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Authority", None));
        ___qtablewidgetitem15 = self.redTrainInfoTable.horizontalHeaderItem(4)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Next Destination", None));
        self.dormontDispatch.setText(QCoreApplication.translate("MainWindow", u"Dispatch a single train", None))
        self.menuNorth_Shore_Extension_CTC_Window.setTitle(QCoreApplication.translate("MainWindow", u"North Shore Extension - CTC Window", None))
    # retranslateUi

