# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CTC_test.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(603, 743)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.locationText = QLabel(self.centralwidget)
        self.locationText.setObjectName(u"locationText")
        self.locationText.setGeometry(QRect(130, 110, 161, 31))
        font = QFont()
        font.setPointSize(11)
        self.locationText.setFont(font)
        self.enterLocation = QLineEdit(self.centralwidget)
        self.enterLocation.setObjectName(u"enterLocation")
        self.enterLocation.setGeometry(QRect(400, 110, 91, 28))
        self.enterSpeed = QLineEdit(self.centralwidget)
        self.enterSpeed.setObjectName(u"enterSpeed")
        self.enterSpeed.setGeometry(QRect(340, 160, 91, 28))
        self.speedText = QLabel(self.centralwidget)
        self.speedText.setObjectName(u"speedText")
        self.speedText.setGeometry(QRect(130, 160, 201, 31))
        self.speedText.setFont(font)
        self.mph = QLabel(self.centralwidget)
        self.mph.setObjectName(u"mph")
        self.mph.setGeometry(QRect(440, 160, 51, 31))
        self.mph.setFont(font)
        self.InputsBox = QFrame(self.centralwidget)
        self.InputsBox.setObjectName(u"InputsBox")
        self.InputsBox.setGeometry(QRect(100, 20, 411, 51))
        self.InputsBox.setAutoFillBackground(False)
        self.InputsBox.setStyleSheet(u"background-color: #B8B8B8\n"
"")
        self.InputsBox.setFrameShape(QFrame.StyledPanel)
        self.InputsBox.setFrameShadow(QFrame.Raised)
        self.Inputs = QLabel(self.InputsBox)
        self.Inputs.setObjectName(u"Inputs")
        self.Inputs.setGeometry(QRect(170, 0, 61, 41))
        font1 = QFont()
        font1.setPointSize(16)
        self.Inputs.setFont(font1)
        self.Inputs.setStyleSheet(u"color: black")
        self.OutputsBox_18 = QFrame(self.centralwidget)
        self.OutputsBox_18.setObjectName(u"OutputsBox_18")
        self.OutputsBox_18.setGeometry(QRect(100, 240, 411, 51))
        self.OutputsBox_18.setAutoFillBackground(False)
        self.OutputsBox_18.setStyleSheet(u"background-color: #B8B8B8")
        self.OutputsBox_18.setFrameShape(QFrame.StyledPanel)
        self.OutputsBox_18.setFrameShadow(QFrame.Raised)
        self.Outputs_2 = QLabel(self.OutputsBox_18)
        self.Outputs_2.setObjectName(u"Outputs_2")
        self.Outputs_2.setGeometry(QRect(170, 0, 81, 41))
        self.Outputs_2.setFont(font1)
        self.Outputs_2.setStyleSheet(u"color: black")
        self.authority = QLabel(self.centralwidget)
        self.authority.setObjectName(u"authority")
        self.authority.setGeometry(QRect(160, 320, 101, 31))
        self.authority.setFont(font)
        self.suggSpeedOutput = QLabel(self.centralwidget)
        self.suggSpeedOutput.setObjectName(u"suggSpeedOutput")
        self.suggSpeedOutput.setGeometry(QRect(330, 320, 171, 31))
        self.suggSpeedOutput.setFont(font)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(70, 360, 471, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.greenLine_2 = QLabel(self.centralwidget)
        self.greenLine_2.setObjectName(u"greenLine_2")
        self.greenLine_2.setGeometry(QRect(150, 380, 91, 31))
        self.greenLine_2.setFont(font)
        self.redLineText = QLabel(self.centralwidget)
        self.redLineText.setObjectName(u"redLineText")
        self.redLineText.setGeometry(QRect(390, 380, 81, 31))
        self.redLineText.setFont(font)
        self.lineSelect = QComboBox(self.centralwidget)
        self.lineSelect.addItem("")
        self.lineSelect.addItem("")
        self.lineSelect.setObjectName(u"lineSelect")
        self.lineSelect.setGeometry(QRect(300, 110, 82, 28))
        self.lineText = QLabel(self.centralwidget)
        self.lineText.setObjectName(u"lineText")
        self.lineText.setGeometry(QRect(320, 80, 41, 31))
        self.lineText.setFont(font)
        self.blockText = QLabel(self.centralwidget)
        self.blockText.setObjectName(u"blockText")
        self.blockText.setGeometry(QRect(420, 80, 51, 31))
        self.blockText.setFont(font)
        self.enterButton = QPushButton(self.centralwidget)
        self.enterButton.setObjectName(u"enterButton")
        self.enterButton.setGeometry(QRect(430, 200, 83, 29))
        self.clearButton = QPushButton(self.centralwidget)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(330, 200, 83, 29))
        self.autoSelect = QCheckBox(self.centralwidget)
        self.autoSelect.setObjectName(u"autoSelect")
        self.autoSelect.setGeometry(QRect(290, 650, 78, 22))
        self.manualSelect = QCheckBox(self.centralwidget)
        self.manualSelect.setObjectName(u"manualSelect")
        self.manualSelect.setGeometry(QRect(370, 650, 61, 22))
        self.maintenanceSelect = QCheckBox(self.centralwidget)
        self.maintenanceSelect.setObjectName(u"maintenanceSelect")
        self.maintenanceSelect.setGeometry(QRect(440, 650, 91, 22))
        self.modesText = QLabel(self.centralwidget)
        self.modesText.setObjectName(u"modesText")
        self.modesText.setGeometry(QRect(240, 650, 41, 16))
        self.red_C2 = QPushButton(self.centralwidget)
        self.red_C2.setObjectName(u"red_C2")
        self.red_C2.setGeometry(QRect(450, 420, 80, 24))
        self.red_C1 = QPushButton(self.centralwidget)
        self.red_C1.setObjectName(u"red_C1")
        self.red_C1.setGeometry(QRect(370, 420, 80, 24))
        self.red_H1_2 = QPushButton(self.centralwidget)
        self.red_H1_2.setObjectName(u"red_H1_2")
        self.red_H1_2.setGeometry(QRect(450, 480, 80, 24))
        self.red_H1_1 = QPushButton(self.centralwidget)
        self.red_H1_1.setObjectName(u"red_H1_1")
        self.red_H1_1.setGeometry(QRect(370, 480, 80, 24))
        self.red_E2 = QPushButton(self.centralwidget)
        self.red_E2.setObjectName(u"red_E2")
        self.red_E2.setGeometry(QRect(450, 450, 80, 24))
        self.red_E1 = QPushButton(self.centralwidget)
        self.red_E1.setObjectName(u"red_E1")
        self.red_E1.setGeometry(QRect(370, 450, 80, 24))
        self.red_H4_2 = QPushButton(self.centralwidget)
        self.red_H4_2.setObjectName(u"red_H4_2")
        self.red_H4_2.setGeometry(QRect(450, 570, 80, 24))
        self.red_H3_2 = QPushButton(self.centralwidget)
        self.red_H3_2.setObjectName(u"red_H3_2")
        self.red_H3_2.setGeometry(QRect(450, 540, 80, 24))
        self.red_H3_1 = QPushButton(self.centralwidget)
        self.red_H3_1.setObjectName(u"red_H3_1")
        self.red_H3_1.setGeometry(QRect(370, 540, 80, 24))
        self.red_J2 = QPushButton(self.centralwidget)
        self.red_J2.setObjectName(u"red_J2")
        self.red_J2.setGeometry(QRect(450, 600, 80, 24))
        self.red_H2_2 = QPushButton(self.centralwidget)
        self.red_H2_2.setObjectName(u"red_H2_2")
        self.red_H2_2.setGeometry(QRect(450, 510, 80, 24))
        self.red_H2_1 = QPushButton(self.centralwidget)
        self.red_H2_1.setObjectName(u"red_H2_1")
        self.red_H2_1.setGeometry(QRect(370, 510, 80, 24))
        self.red_J1 = QPushButton(self.centralwidget)
        self.red_J1.setObjectName(u"red_J1")
        self.red_J1.setGeometry(QRect(370, 600, 80, 24))
        self.red_H4_1 = QPushButton(self.centralwidget)
        self.red_H4_1.setObjectName(u"red_H4_1")
        self.red_H4_1.setGeometry(QRect(370, 570, 80, 24))
        self.green_G2 = QPushButton(self.centralwidget)
        self.green_G2.setObjectName(u"green_G2")
        self.green_G2.setGeometry(QRect(210, 450, 80, 24))
        self.green_C2 = QPushButton(self.centralwidget)
        self.green_C2.setObjectName(u"green_C2")
        self.green_C2.setGeometry(QRect(210, 420, 80, 24))
        self.green_C1 = QPushButton(self.centralwidget)
        self.green_C1.setObjectName(u"green_C1")
        self.green_C1.setGeometry(QRect(130, 420, 80, 24))
        self.green_J1_2 = QPushButton(self.centralwidget)
        self.green_J1_2.setObjectName(u"green_J1_2")
        self.green_J1_2.setGeometry(QRect(210, 480, 80, 24))
        self.green_N1 = QPushButton(self.centralwidget)
        self.green_N1.setObjectName(u"green_N1")
        self.green_N1.setGeometry(QRect(130, 570, 80, 24))
        self.green_J2_2 = QPushButton(self.centralwidget)
        self.green_J2_2.setObjectName(u"green_J2_2")
        self.green_J2_2.setGeometry(QRect(210, 510, 80, 24))
        self.green_N2 = QPushButton(self.centralwidget)
        self.green_N2.setObjectName(u"green_N2")
        self.green_N2.setGeometry(QRect(210, 570, 80, 24))
        self.green_J1_1 = QPushButton(self.centralwidget)
        self.green_J1_1.setObjectName(u"green_J1_1")
        self.green_J1_1.setGeometry(QRect(130, 480, 80, 24))
        self.green_M1 = QPushButton(self.centralwidget)
        self.green_M1.setObjectName(u"green_M1")
        self.green_M1.setGeometry(QRect(130, 540, 80, 24))
        self.green_J2_1 = QPushButton(self.centralwidget)
        self.green_J2_1.setObjectName(u"green_J2_1")
        self.green_J2_1.setGeometry(QRect(130, 510, 80, 24))
        self.green_G1 = QPushButton(self.centralwidget)
        self.green_G1.setObjectName(u"green_G1")
        self.green_G1.setGeometry(QRect(130, 450, 80, 24))
        self.green_M2 = QPushButton(self.centralwidget)
        self.green_M2.setObjectName(u"green_M2")
        self.green_M2.setGeometry(QRect(210, 540, 80, 24))
        self.red_text_C = QLabel(self.centralwidget)
        self.red_text_C.setObjectName(u"red_text_C")
        self.red_text_C.setGeometry(QRect(330, 420, 16, 16))
        self.red_text_E = QLabel(self.centralwidget)
        self.red_text_E.setObjectName(u"red_text_E")
        self.red_text_E.setGeometry(QRect(330, 450, 16, 16))
        self.red_text_H1 = QLabel(self.centralwidget)
        self.red_text_H1.setObjectName(u"red_text_H1")
        self.red_text_H1.setGeometry(QRect(330, 480, 16, 16))
        self.red_textH2 = QLabel(self.centralwidget)
        self.red_textH2.setObjectName(u"red_textH2")
        self.red_textH2.setGeometry(QRect(330, 510, 16, 16))
        self.red_textH3 = QLabel(self.centralwidget)
        self.red_textH3.setObjectName(u"red_textH3")
        self.red_textH3.setGeometry(QRect(330, 540, 16, 16))
        self.red_text_H4 = QLabel(self.centralwidget)
        self.red_text_H4.setObjectName(u"red_text_H4")
        self.red_text_H4.setGeometry(QRect(330, 570, 16, 16))
        self.red_text_J = QLabel(self.centralwidget)
        self.red_text_J.setObjectName(u"red_text_J")
        self.red_text_J.setGeometry(QRect(330, 600, 16, 16))
        self.green_text_N = QLabel(self.centralwidget)
        self.green_text_N.setObjectName(u"green_text_N")
        self.green_text_N.setGeometry(QRect(90, 570, 16, 16))
        self.green_text_C = QLabel(self.centralwidget)
        self.green_text_C.setObjectName(u"green_text_C")
        self.green_text_C.setGeometry(QRect(90, 420, 16, 16))
        self.green_text_M = QLabel(self.centralwidget)
        self.green_text_M.setObjectName(u"green_text_M")
        self.green_text_M.setGeometry(QRect(90, 540, 16, 16))
        self.green_text_G = QLabel(self.centralwidget)
        self.green_text_G.setObjectName(u"green_text_G")
        self.green_text_G.setGeometry(QRect(90, 450, 16, 16))
        self.green_text_J1 = QLabel(self.centralwidget)
        self.green_text_J1.setObjectName(u"green_text_J1")
        self.green_text_J1.setGeometry(QRect(90, 480, 16, 16))
        self.green_text_J2 = QLabel(self.centralwidget)
        self.green_text_J2.setObjectName(u"green_text_J2")
        self.green_text_J2.setGeometry(QRect(90, 510, 16, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 603, 21))
        self.menuCTC_Dispatcher_Test_UI = QMenu(self.menubar)
        self.menuCTC_Dispatcher_Test_UI.setObjectName(u"menuCTC_Dispatcher_Test_UI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuCTC_Dispatcher_Test_UI.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.locationText.setText(QCoreApplication.translate("MainWindow", u"Enter Train Location:", None))
        self.enterSpeed.setText("")
        self.speedText.setText(QCoreApplication.translate("MainWindow", u"Enter Suggested Speed:", None))
        self.mph.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.Inputs.setText(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.Outputs_2.setText(QCoreApplication.translate("MainWindow", u"Outputs", None))
        self.authority.setText(QCoreApplication.translate("MainWindow", u"Authority: --mi", None))
        self.suggSpeedOutput.setText(QCoreApplication.translate("MainWindow", u"Suggested Speed: --mph", None))
        self.greenLine_2.setText(QCoreApplication.translate("MainWindow", u"Green Line", None))
        self.redLineText.setText(QCoreApplication.translate("MainWindow", u"Red Line", None))
        self.lineSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"Green", None))
        self.lineSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))

        self.lineText.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.blockText.setText(QCoreApplication.translate("MainWindow", u"Block", None))
        self.enterButton.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.clearButton.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.autoSelect.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.manualSelect.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.maintenanceSelect.setText(QCoreApplication.translate("MainWindow", u"Maintenance", None))
        self.modesText.setText(QCoreApplication.translate("MainWindow", u"Modes:", None))
        self.red_C2.setText(QCoreApplication.translate("MainWindow", u"9-Yard", None))
        self.red_C1.setText(QCoreApplication.translate("MainWindow", u"9-10", None))
        self.red_H1_2.setText(QCoreApplication.translate("MainWindow", u"27-76", None))
        self.red_H1_1.setText(QCoreApplication.translate("MainWindow", u"27-28", None))
        self.red_E2.setText(QCoreApplication.translate("MainWindow", u"1-16", None))
        self.red_E1.setText(QCoreApplication.translate("MainWindow", u"15-16", None))
        self.red_H4_2.setText(QCoreApplication.translate("MainWindow", u"43-67", None))
        self.red_H3_2.setText(QCoreApplication.translate("MainWindow", u"38-71", None))
        self.red_H3_1.setText(QCoreApplication.translate("MainWindow", u"38-39", None))
        self.red_J2.setText(QCoreApplication.translate("MainWindow", u"52-66", None))
        self.red_H2_2.setText(QCoreApplication.translate("MainWindow", u"32-72", None))
        self.red_H2_1.setText(QCoreApplication.translate("MainWindow", u"32-33", None))
        self.red_J1.setText(QCoreApplication.translate("MainWindow", u"52-53", None))
        self.red_H4_1.setText(QCoreApplication.translate("MainWindow", u"43-44", None))
        self.green_G2.setText(QCoreApplication.translate("MainWindow", u"29-150", None))
        self.green_C2.setText(QCoreApplication.translate("MainWindow", u"1-13", None))
        self.green_C1.setText(QCoreApplication.translate("MainWindow", u"12-13", None))
        self.green_J1_2.setText(QCoreApplication.translate("MainWindow", u"57-58", None))
        self.green_N1.setText(QCoreApplication.translate("MainWindow", u"85-86", None))
        self.green_J2_2.setText(QCoreApplication.translate("MainWindow", u"Yard-63", None))
        self.green_N2.setText(QCoreApplication.translate("MainWindow", u"85-100", None))
        self.green_J1_1.setText(QCoreApplication.translate("MainWindow", u"57-Yard", None))
        self.green_M1.setText(QCoreApplication.translate("MainWindow", u"76-77", None))
        self.green_J2_1.setText(QCoreApplication.translate("MainWindow", u"62-63", None))
        self.green_G1.setText(QCoreApplication.translate("MainWindow", u"29-30", None))
        self.green_M2.setText(QCoreApplication.translate("MainWindow", u"77-101", None))
        self.red_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.red_text_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.red_text_H1.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH2.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_textH3.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_text_H4.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.red_text_J.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.green_text_N.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.green_text_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.green_text_M.setText(QCoreApplication.translate("MainWindow", u"M", None))
        self.green_text_G.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.green_text_J1.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.green_text_J2.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.menuCTC_Dispatcher_Test_UI.setTitle(QCoreApplication.translate("MainWindow", u"CTC Dispatcher - Test UI", None))
    # retranslateUi

