# Form implementation generated from reading ui file 'testthis.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_test(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(400, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=test)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 20, 265, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reda = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.reda.setObjectName("reda")
        self.horizontalLayout.addWidget(self.reda)
        self.yellowa = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.yellowa.setObjectName("yellowa")
        self.horizontalLayout.addWidget(self.yellowa)
        self.greena = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.greena.setObjectName("greena")
        self.horizontalLayout.addWidget(self.greena)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=test)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 110, 265, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.redb = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.redb.setObjectName("redb")
        self.horizontalLayout_2.addWidget(self.redb)
        self.yellowb = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.yellowb.setObjectName("yellowb")
        self.horizontalLayout_2.addWidget(self.yellowb)
        self.greenb = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.greenb.setObjectName("greenb")
        self.horizontalLayout_2.addWidget(self.greenb)
        self.section = QtWidgets.QComboBox(parent=test)
        self.section.setGeometry(QtCore.QRect(180, 210, 82, 28))
        self.section.setObjectName("section")
        self.block = QtWidgets.QComboBox(parent=test)
        self.block.setGeometry(QtCore.QRect(300, 210, 82, 28))
        self.block.setObjectName("block")

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "Form"))
        self.reda.setText(_translate("test", "reda"))
        self.yellowa.setText(_translate("test", "yellowa"))
        self.greena.setText(_translate("test", "greena"))
        self.redb.setText(_translate("test", "redb"))
        self.yellowb.setText(_translate("test", "yellowb"))
        self.greenb.setText(_translate("test", "greenb"))
